### ISSUE TITLE
Cannot change to second tab in Tabbed view

### ISSUE THREAD

**Issue by entodoays** [bibletime/bibletime#91] opened 2017-01-25 07:33 UTC
In Bibletime 2.11, when using tabbed view, it is not possible to switch tabs. The first tab always remains selected. Clicking on the second tab has no effect.
I'm using 1 tab with the TSK module and 1 tab with 2 bible texts side by side. In the 1st tab, I've selected the synchronize to selected window option.
I'm testing on Archlinux 64 bit.

**Comment by gholmlund** [comment] 2017-01-25 17:43
Confirmed on ubuntu 16.10 and arch. Seems to be triggered by any usage of "synchronize to active Bible window".

**Comment by jaakristioja** [comment] 2017-01-25 21:09
I can also confirm this on Gentoo Linux with master branch. Note that in non-tabbed mode, when another verse is selected or opened in the window with the Bibles, the synchronized commentary window gets focus, which it should not.

**Comment by gholmlund** [comment] 2017-01-26 05:39
I captured the call stack that causes the synchronized commentary window to be focused. In QWebEngineView the call to update the page (setHtml) causes the window to be focused. This is for the non-tabbed case, but I think the tabbed case would be almost the same.

24 **content::WebContentsImpl::Focus** 
25 QtWebEngineCore::WebContentsAdapter::setContent
26 QWebEnginePage::setContent
27 QWebEnginePage::setHtml 
28 **QWebEngineView::setHtml**
29 BtHtmlReadDisplay::setText 
30 CReadWindow::lookupSwordKey 
31 CReadWindow::qt_static_metacall
32 QMetaObject::activate 
33 QMetaObject::activate
34 CKeyChooser::keyChanged
35 CBibleKeyChooser::setKey
36 CDisplayWindow::lookupModKey
37 CDisplayWindow::lookupKey 
38 **CBibleReadWindow::syncWindows**
39 CBibleReadWindow::lookupSwordKey

The complete call stack is available here:
[bibletime_bug2.txt](https://github.com/bibletime/bibletime/files/731601/bibletime_bug2.txt)

The problem is all in Qt. I have not figured out what to do about this.

**Comment by gholmlund** [comment] 2017-01-27 00:01
In CBibleReadWindow::syncWindows we know the active window. If it is changed during syncing it is changed back to the original active window. Closing.

**Closed by gholmlund** 2017-01-27 00:01 UTC
Labels: component: Qt related, type: BUG

**Comment by jaakristioja** [comment] 2017-05-25 08:16
Fixed in 34c0fbb85abdeca19d16b316f1f3c615f03f2618.
