### ISSUE TITLE
Display not correct when BibleTime is initially opened

### ISSUE THREAD

**Issue by ArnoVersfeld** [bibletime/bibletime#403] opened 2022-08-08 10:09 UTC
**Bug description**
BibleTime display setting:     Christmastide.css
The display mostly, it varies from day to day, is not what I get when I page down or up through the text.
The background should be off-white and the text green.
As shown in the attached video some of the text is black instead of green and some of the verse numbers are smaller than others. 
Sometimes portions of the background is white instead of off-white
When I scroll up or down some distance and then go back to where the display opened the background has changed to off white and the text green and the verse numbers all the correct size.
Further I find large gaps between some verses.
I have tested using other translations and get exactly the same type of results every time.

**Steps to reproduce**
I have tested using other translations and get exactly the same type of results every time.

**Expected behavior**
The background should be off-white and the text green, the verse numbers the same size while the gaps between verses should not be there

**Screenshots**
Please see attached video

**System information:**
 - OS and OS version: Ubuntu 20.04
 - OS type:  64bit
 - GNOME version:  3.36.8
 - BibleTime Version:  3.0.3
 - How BibleTime was installed:  Snap
 - Versions of modules related to the crash:   n/a 
 - (If compiled from source) Sword Version
 - (If compiled from source) Qt Version

**Additional context**
Add any other context about the problem here, e.g. including output of `bibletime --debug` and/or backtraces in case of crashes.
[Screencast from 08-08-2022 12:02:39.webm](https://user-images.githubusercontent.com/33600932/183394073-1dd9610e-7c1b-4e0f-af1b-2af8557ae941.webm)

**Comment by ArnoVersfeld** [comment] 2022-08-15 04:20
Yesterday I upgraded my OS from Ubuntu 20.04 to 22.04 with a GNOME version 42.2.
The problem described is still the same. What I did find when I changed to another translation the spacing between verses improved but the smaller verse numbers when BibleTime is initially opened is still the same.

**Comment by ArnoVersfeld** [comment] 2022-10-26 07:29
Thank you everyone involved in getting the bug fixed !
The background colour issue has been corrected.
The verse number issue has been fixed.
The large gaps between verses is still a problem
The Bible version have been using is engWEBBE2015. I opened a copy of KJV at the same scripture portion and found everything displayed normally, no unusually large gaps at places at all.
[spacing error 26-10-2022..pdf](https://github.com/bibletime/bibletime/files/9867153/spacing.error.26-10-2022.pdf)

**Comment by jaakristioja** [comment] 2022-12-04 11:39
> Thank you everyone involved in getting the bug fixed ! The background colour issue has been corrected. The verse number issue has been fixed.

I don't think we did anything in purpose to fix these. Probably some Qt or display rendering issues that got fixed in your Ubuntu.

> The large gaps between verses is still a problem The Bible version have been using is engWEBBE2015. I opened a copy of KJV at the same scripture portion and found everything displayed normally, no unusually large gaps at places at all. [spacing error 26-10-2022..pdf](https://github.com/bibletime/bibletime/files/9867153/spacing.error.26-10-2022.pdf)

I think this might be a problem specifically with the engWEBBE2015 module, which includes a gap of some sort in such places, e.g. before Ephesians 1:3. BibleTime should probably collapse this, but fails to do this for some reason.

**Comment by jaakristioja** [comment] 2022-12-04 11:53
Output from `diatheke` (a tool bundled with libsword) show that Ephesians 1:2 from engWEBBE2015eb contains some strange `<div eID="gen36276" type="x-p"/>` element, which might be the cause for this issue.

```
$ diatheke -b engWEBBE2015eb -f HTML -k Eph 1:2
<html><head><meta http-equiv="content-type" content="text/html" charset="UTF-8" lang="en" xml:lang="en"/>
<style type="text/css"></style></head><body>Ephesians 1:2: <span style="font:Gentium Plus;" ><w savlm="strong:G5485">Grace</w> <w savlm="strong:G2532">to</w> <w savlm="strong:G5210">you</w> <w savlm="strong:G2532">and</w> <w savlm="strong:G1515">peace</w> <w savlm="strong:G0575">from</w> <w savlm="strong:G2316">God</w> <w savlm="strong:G2316">our</w> <w savlm="strong:G3962">Father</w> <w savlm="strong:G2532">and</w> <w savlm="strong:G2532">the</w> <w savlm="strong:G2962">Lord</w> <w savlm="strong:G2424">Jesus</w> <w savlm="strong:G5547">Christ</w>. <div eID="gen36276" type="x-p"/></span><br />
(engWEBBE2015eb)
</body></html>
```

So I'd say that this is more an issue with the engWEBBE2015eb module, than with BibleTime.

Working around specific module issues is currently out of scope for us. We might in the future have a better framework for dealing with such module quirks, but we currently have no resources to tackle this by ourselves in BibleTime.

It is easier to fix the module, hence I suggest to instead contact the engWEBBE2015eb module authors for the gap issue.

**Closed by jaakristioja** 2022-12-04 11:53 UTC
Labels: type: BUG, component: Backend
