### ISSUE TITLE
Qt "More Info..." tab is blank

### ISSUE THREAD

**Issue by bontibon** [bibletime/bibletime#92] opened 2017-01-25 16:36 UTC
Version: d755be9ffd394a99b7cbb7e2ce7d3799ea8c807a
Qt version: 5.7.1

To reproduce: Help -> About BibleTime -> Qt -> More Info...
The view is blank (completely white):

![image](https://cloud.githubusercontent.com/assets/110883/22299511/bbadf698-e2fa-11e6-950f-9d5bb40496a7.png)

**Comment by gholmlund** [comment] 2017-01-25 18:04
I note that the version shown is the master branch HEAD. I tried this and stable-2.11 using ubuntu 16.10 and Qt 5.7.1. I could not reproduce this problem.

**Comment by jaakristioja** [comment] 2017-01-25 20:59
I'm unable to reproduce with the same revision on Gentoo Linux using Qt 5.7.1 as well.

**Comment by bontibon** [comment] 2017-01-25 22:30
I'm on Arch Linux.

In doing some debugging, it appears that `BtAboutDialog::linkClicked` does not get called for that link, but does for all others in the about dialog.

**Comment by jaakristioja** [comment] 2017-01-26 08:52
Please disregard my comment about not able to reproduce. I misunderstood the issue late last night. I can now reproduce.

Clicking on the "More info..." link should open a new "About Qt" dialog window instead of changing the contents of that HTML view widget. Instead it seems to switch the HTML view to a blank page. Maybe related to the switch from QWebView to QWebEngineView. It seems that the `BtAboutDialog::linkClicked` slot does not get called at all.

**Comment by gholmlund** [comment] 2017-01-27 02:33
QWebEnginePage only works with links beginning with http, https, and ftp.
https://bugreports.qt.io/browse/QTBUG-50922

**Comment by gholmlund** [comment] 2017-01-27 05:15
QWebKit and QWebEngine were both broken for different reasons. Fixed and tested with Qt 5.5, 5.6, 5.7, and 5.8. Closing.

**Closed by gholmlund** 2017-01-27 05:15 UTC
Labels: component: Qt related, type: BUG
