### ISSUE TITLE
Display of more than 4 parallel works on macOS corrupts when scrolled up

### ISSUE THREAD

**Issue by jmarshallidau** [bibletime/bibletime#329] opened 2021-06-30 01:00 UTC
macOS 11.4
BibleTime 3.0.0

If I have more than 4 bibles open alongside each other and scroll back, the text in all of the bibles is overwritten and illegible. No problem with BibleTime 2.11.2. Problem started with upgrade to 3.0.0 and has persisted through the past few macOS upgrades. Reverting to BibleTime 2.11.2 clears the problem. It's adding the 5th bible that kills it.
<img width="1288" alt="Screen Shot 2021-06-30 at 10 58 52" src="https://user-images.githubusercontent.com/86695380/123886226-56399900-d992-11eb-96fd-6020aa89ad36.png">

**Comment by jmarshallidau** [comment] 2021-06-30 01:02
Display returns to normal when 5th bible is removed.

**Comment by gholmlund** [comment] 2021-06-30 01:12
This is a duplicate of #268. It was fixed last September and will be in the next released version.

**Closed by gholmlund** 2021-06-30 01:12 UTC
Labels: resolution: DUPLICATE
