### ISSUE TITLE
Last Bibletime don't show text at all

### ISSUE THREAD

**Issue by DrMoriarty** [bibletime/bibletime#144] opened 2018-06-10 05:43 UTC
Hello! I used to use bibletime 2.10.1 for a long time. It had several issues but none of them was really critical.
Today I updated bibletime to 2.11.1 and it was epic fail. Ok, absent of russian translation (which worked in 2.10.1) is annoying but not critical.
The main issue, that it doesn't show me any text! I have a lot of texts and books installed in my `/Users/vasya/Library/Application Support/Sword` (I installed them in old Bibletime and in Eloquent)
![2018-06-10 8 32 27](https://user-images.githubusercontent.com/1177068/41198580-8f8dbfc0-6c89-11e8-8552-cdd523c77eb2.png)
When I try to use install manager I select all remote sources, select russian language and it doesn't show me any bible comments! Why I can not do with bibletime 2.11.1 what I successfully did with bibletime 2.10.1?
![2018-06-10 8 40 34](https://user-images.githubusercontent.com/1177068/41198595-1e8ab8ea-6c8a-11e8-9e85-8e2c0f6a2fa7.png)

My OS: macosx 10.13.4

**Comment by DrMoriarty** [comment] 2018-06-10 06:09
Just reinstalled old version
![2018-06-10 9 09 02](https://user-images.githubusercontent.com/1177068/41198761-ff5b7280-6c8d-11e8-9d73-ef6ee67e2f11.png)
Bibletime 2.10.1 the best!

**Comment by gholmlund** [comment] 2018-06-11 01:19
I cannot reproduce this on linux. Perhaps it is a Mac only problem. I suggest reinstalling 2.11.1 in case a install time problem occurred. Then go back to 2.10 if necessary.

**Comment by shtjonathan** [comment] 2018-06-11 08:55
I can confirm this issue on Arch Linux.
I cannot currently access my setup at the moment, but I can confirm that although the windows show up, there was no text shown at all on a freshly installed BibleTime on a freshly installed and updated Arch Linux system (on a Raspberry Pi 3B+). All text views remain empty.

I noticed some people having the same "no text shown" problem on other Linux systems (Ubuntu 18.04, Manjaro 17.10 KDE) as well, see issue #140 at thread:
"Re: [bibletime/bibletime] No text in window after upgrade to Qt 5.11 (#140)"

And also (maybe related?) after trying to change display and font settings etc., BibleTime showed some corrupted text and then crashed the whole windowing system, causing all other programs to crash/disappear as well.

**Comment by DrMoriarty** [comment] 2018-06-11 13:37
@gholmlund I'm pretty shure that this is not an install time problem. I reinstalled BibleTime 2.11.1, I completely removed application settings (`~/Library/Application Support/BibleTime`), I changed the default application font in settings to Times New Roman. Nothing helped.
![2018-06-11 16 33 49](https://user-images.githubusercontent.com/1177068/41234740-ac70cfc6-6d95-11e8-8117-c547757204e4.png)

**Comment by gholmlund** [comment] 2018-06-11 13:42
Yes, bug #140 is about window text not working with Qt5.11. This bug is fixed, but not released  yet. It is not related to this issue since the Mac is not using Qt 5.11.

**Comment by gholmlund** [comment] 2018-06-11 13:45
@DrMoriaty Thank you for trying the reinstall. I suspected it would not help, but needed to rule it out. At this time I don't have any other ideas about the problem.

**Comment by DrMoriarty** [comment] 2018-06-11 14:04
Also I checked other releases, but all releases still 2.11-beta1 until 2.11.0 are crashed on start.

**Comment by gholmlund** [comment] 2018-06-11 14:09
Would you be able to run 2.11.1 from the command line and use the " --debug" option. It should report more messages that may tell us the issue.

**Comment by DrMoriarty** [comment] 2018-06-11 14:16
```
bash-3.2$ ./BibleTime --debug
(BibleTime 2.11.1) Debug: Using sword locales dir:  "/Applications/BibleTime.app/Contents/share/sword/locales.d"
LocaleMgr::loadConfigDir loading /Applications/BibleTime.app/Contents/share/sword/locales.d
LOOKING UP MODULE CONFIGURATION...
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Overriding any systemwide or ~/.sword/ sword.conf with one found in current directory.
DataPath in ./sword.conf is set to /Users/vasya/Library/Application Support/Sword/.
Checking for mods.conf in DataPath...
Checking for mods.d in DataPath...
found.
LOOKING UP MODULE CONFIGURATION COMPLETE.
dyld: Library not loaded: /usr/local/Cellar/qt/5.10.0_1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
dyld: Library not loaded: /usr/local/Cellar/qt/5.10.0_1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

[65244:74499:0611/171522.352534:ERROR:service_manager_context.cc(171)] Attempting to run unsupported native service: /Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[65244:74499:0611/171522.352782:ERROR:service_manager_context.cc(171)] Attempting to run unsupported native service: /Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[65244:74499:0611/171522.354841:ERROR:service_manager_context.cc(171)] Attempting to run unsupported native service: /Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[65244:74499:0611/171522.354947:ERROR:service_manager_context.cc(171)] Attempting to run unsupported native service: /Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
```

**Comment by DrMoriarty** [comment] 2018-06-11 14:20
I noticed that file `/Applications/BibleTime.app/Contents/MacOS/libsword-1.8.0.dylib` is a broken symlink which links to `../Cellar/sword/1.8.0/lib/libsword-1.8.0.dylib`
Can it be the reason of a problem?

**Comment by gholmlund** [comment] 2018-06-11 14:27
I believe that the following messages showning QtWebEngine not loading property, is the issue.

dyld: Library not loaded: /usr/local/Cellar/qt/5.10.0_1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
dyld: Library not loaded: /usr/local/Cellar/qt/5.10.0_1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found

This seems to be a Mac specific issue and I don't use a Mac. Can anyone else help with this?

**Comment by DrMoriarty** [comment] 2018-06-11 14:30
I have no installed qt libraries yet, but I can try to install them and rebuild bibletime from sources.

**Comment by DrMoriarty** [comment] 2018-06-11 14:39
I made symlink `/usr/local/Cellar/qt/5.10.0_1/lib` which link to `/Applications/BibleTime.app/Contents/Frameworks`
When start it shows me this log:
```
bash-3.2$ ./BibleTime --debug
(BibleTime 2.11.1) Debug: Using sword locales dir:  "/Applications/BibleTime.app/Contents/share/sword/locales.d"
LocaleMgr::loadConfigDir loading /Applications/BibleTime.app/Contents/share/sword/locales.d
LOOKING UP MODULE CONFIGURATION...
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Overriding any systemwide or ~/.sword/ sword.conf with one found in current directory.
DataPath in ./sword.conf is set to /Users/vasya/Library/Application Support/Sword/.
Checking for mods.conf in DataPath...
Checking for mods.d in DataPath...
found.
LOOKING UP MODULE CONFIGURATION COMPLETE.
dyld: Library not loaded: @executable_path/../Frameworks/QtQuick.framework/Versions/5/QtQuick
  Referenced from: /usr/local/Cellar/qt/5.10.0_1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Reason: image not found
dyld: Library not loaded: @executable_path/../Frameworks/QtQuick.framework/Versions/5/QtQuick
  Referenced from: /usr/local/Cellar/qt/5.10.0_1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Reason: image not found
[16654:55811:0611/173438.399690:ERROR:service_manager_context.cc(171)] Attempting to run unsupported native service: /Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[16654:55811:0611/173438.399884:ERROR:service_manager_context.cc(171)] Attempting to run unsupported native service: /Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[16654:55811:0611/173438.401053:ERROR:service_manager_context.cc(171)] Attempting to run unsupported native service: /Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
[16654:55811:0611/173438.401315:ERROR:service_manager_context.cc(171)] Attempting to run unsupported native service: /Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Versions/5/content_renderer.service
```

(still no any text in bible views)

**Comment by gholmlund** [comment] 2018-06-11 14:43
The Qt libraries should be bundled within the BibleTime install. Installing other Qt libraries won't help.

**Comment by DrMoriarty** [comment] 2018-06-11 14:53
I googled the error and people said that highly likely not all necessary libraries was packed with the bundle. So it is installation bundle packing problem. (I'm a programmer but I don't use qt still version 4.x)

**Comment by DrMoriarty** [comment] 2018-06-11 15:17
I installed qt 5.10.1 from mac ports, made symlink in `/usr/local/Cellar/qt/5.10.0_1/lib` points to `/opt/local/libexec/qt5/lib` and BINGO!!! it worked!
![2018-06-11 18 14 47](https://user-images.githubusercontent.com/1177068/41240613-9a3ee35c-6da3-11e8-995b-e6afa54494c3.png)

So it definitely the installation bundling problem.

**Comment by DrMoriarty** [comment] 2018-06-11 15:25
As you can see on my screenshot russian translation also works very well!

**Comment by mhjacks** [comment] 2018-06-12 22:47
I'm seeing the same thing.  I've used BibleTime on Linux (KDE) for a long time but find myself in Mac-land at the moment.  I also know a bit about toolchains but not much about Mac specifics.  @gholmlund what kind of help are you looking for?  I would be happy to help if I can.

**Comment by gholmlund** [comment] 2018-06-12 23:37
I am hoping the person who built the Mac version to jump in here. The help we need is to run the Mac build scripts and be able to find the problem. Not knowing the Mac, I can't be more specific.

**Comment by mgruner** [comment] 2018-06-13 17:36
Can you please try again with https://github.com/bibletime/bibletime/releases/download/v2.11.1/BibleTime.2.11.1-1.dmg?

**Comment by DrMoriarty** [comment] 2018-06-13 21:14
@mgruner This new build shows me the same problem:
```
dyld: Library not loaded: /usr/local/Cellar/qt/5.10.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore
  Referenced from: /Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
```
So all web views have no any texts.
It starts working only when I created symlink `/usr/local/Cellar/qt/5.10.1/lib` which points to my local qt5.10 installation.

I checked all libraries in the application bundle and found that the only binary which have links to /usr/local/Cellar/qt is the `/Applications/BibleTime.app/Contents/Frameworks/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess`
```
bash-3.2$ otool -L QtWebEngineProcess 
QtWebEngineProcess:
	/usr/local/Cellar/qt/5.10.1/lib/QtWebEngineCore.framework/Versions/5/QtWebEngineCore (compatibility version 5.10.0, current version 5.10.1)
	/usr/local/Cellar/qt/5.10.1/lib/QtQuick.framework/Versions/5/QtQuick (compatibility version 5.10.0, current version 5.10.1)
	/usr/local/Cellar/qt/5.10.1/lib/QtGui.framework/Versions/5/QtGui (compatibility version 5.10.0, current version 5.10.1)
	/usr/local/Cellar/qt/5.10.1/lib/QtCore.framework/Versions/5/QtCore (compatibility version 5.10.0, current version 5.10.1)
	/System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/usr/local/Cellar/qt/5.10.1/lib/QtQml.framework/Versions/5/QtQml (compatibility version 5.10.0, current version 5.10.1)
	/usr/local/Cellar/qt/5.10.1/lib/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.10.0, current version 5.10.1)
	/usr/local/Cellar/qt/5.10.1/lib/QtWebChannel.framework/Versions/5/QtWebChannel (compatibility version 5.10.0, current version 5.10.1)
	/usr/local/Cellar/qt/5.10.1/lib/QtPositioning.framework/Versions/5/QtPositioning (compatibility version 5.10.0, current version 5.10.1)
	/System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
	/System/Library/Frameworks/AGL.framework/Versions/A/AGL (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
```

I also found this letter https://www.riverbankcomputing.com/pipermail/pyqt/2016-April/037179.html where described a problem like the our one.

**Comment by mgruner** [comment] 2018-06-19 06:45
@DrMoriarty very helpful, thank you. I need to investigate this further.

**Comment by mgruner** [comment] 2018-06-19 07:53
https://stackoverflow.com/questions/46430930/how-to-make-macdeployqt-change-the-library-names-inside-qtwebengineprocess-app-w

**Comment by mgruner** [comment] 2018-06-19 14:38
Can you please try again with the new 2.11.2 build? I believe the issue is fixed now. The build relies on the official Qt 5.11.1 packages now, rather than on homebrew.

**Closed by mgruner** 2018-06-19 14:38 UTC
Labels: component: CMake-based build system, help wanted, type: BUG

**Comment by DrMoriarty** [comment] 2018-06-20 07:04
@mgruner Thank you very much!

**Comment by shtjonathan** [comment] 2018-07-10 12:31
Hello all,

A while earlier I had reported that Bibletime on Arch Linux on Raspberry Pi appeared to have the same issue (no text at all shown).

But this turned out to be caused by an outdated Arch Linux package repository mirror (the standard one).

When a friend of mine looked at my Arch installation, he found it quickly.
After changing the package repository mirror and updating my system, the problem with Bibletime was also gone!

Sincerely,
Samuel
