### ISSUE TITLE
[BUG] Open a crossreference in the bible window

### ISSUE THREAD

**Issue by LAfricain** [bibletime/bibletime#370] opened 2022-01-21 12:12 UTC
When I click on a cross-reference in the daily devotional frelitcal2022, I have only the first verse displayed in the mag. It would be very interesting to have all the passage opened in a window. I know the drag and drop but sometimes it's not easy to use.

Maybe it's already possible,  but I can't find how.

**Comment by jaakristioja** [comment] 2022-01-30 18:36
This seems to be a duplicate of #348. Please reopen if it is a different issue.

**Comment by LAfricain** [comment] 2022-01-30 20:06
It's not really a duplicate. But in fact if you solve #348 it will be already better. But for me if the text can be opened in a new  window, this can be interesting when we want to continue the reading of the same book.

**Comment by jaakristioja** [comment] 2022-04-24 22:11
Hmm... I think I see what you mean. By the looks of it, clicking on the cross-reference actually seems to try to navigate to the reference, but in the daily devotional itself, because the title of the subwindow/tab changes, but since it contains no such key, nothing else seems to happen. I suppose the expected behavior would be to open the passage in a new subwindow/tab with the standard bible.

**Comment by jaakristioja** [comment] 2022-05-12 20:51
@gholmlund Could you please take a look at this?

As far as I can tell, the logic to open the link follows this route:

https://github.com/bibletime/bibletime/blob/99b95ef14d81347d357a69b269cb4255bb221e60/src/frontend/display/modelview/DisplayView.qml#L111-L122
https://github.com/bibletime/bibletime/blob/99b95ef14d81347d357a69b269cb4255bb221e60/src/frontend/display/modelview/btqmlinterface.cpp#L338-L347
https://github.com/bibletime/bibletime/blob/99b95ef14d81347d357a69b269cb4255bb221e60/src/frontend/display/modelview/btqmlscrollview.cpp#L69
https://github.com/bibletime/bibletime/blob/99b95ef14d81347d357a69b269cb4255bb221e60/src/frontend/display/btmodelviewreaddisplay.cpp#L93-L98

It is slightly different in the stable-3.0 branch, but the route seems to be missing a check whether the clicked bible reference can actually be opened in the current window. The missing logic needs to be added, but I'm currently unsure where to. Perhaps you are more familiar with this code? Thanks!

**Comment by jaakristioja** [comment] 2022-05-13 18:25
After some more examination, and filing of issues #386 and #387 in response to some of the symptoms on the level of source code, it feels that fixing this without introducing new bugs requires quite a lot of refactoring, likely more that distribution package maintainers would be willing pull in for bugfix releases. Additionally, since this issue has turned out to be more complex than I expected and it conflicts with my plan to release 3.0.3 this week, so I'm adjusting the milestone from 3.0.3 to 3.1.0.

**Closed** 2022-06-04 22:52 UTC
Labels: type: BUG, component: Frontend

**Comment by gholmlund** [comment] 2022-06-04 23:08
Clicking a link will change to that reference if the current module is a Bible. If not, it uses the Standard works Bible and opens a new window. If no standard Bible is configured, a dialog opens asking that a standard Bible be configured.
