### ISSUE TITLE
JavaScript error

### ISSUE THREAD

**Issue by mgruner** [bibletime/bibletime#57] opened 2016-04-19 18:22 UTC
Current BibleTime triggers the following warning when I open Bibles:
```(BibleTime 2.10.0_rc1+dd3dbc0f91bfcf45e74d55e00638858a1f32430b) WARNING: javascript console : "Uncaught TypeError: channel.execCallbacks[message.id] is not a function"```
I am using QT 5.6.

**Comment by gholmlund** [comment] 2016-04-20 23:24
I am not able to reproduce this. I am trying on linux. Do you see any bad behavior of BibleTime that might be associated with this warning.

The execCallbacks function is defined and used in qwebchannel.js. This file is a Qt file in the Qt resources. When using QWebEngine we load this file. It must be loaded before our btwebengine.js javascript file is loaded. 

Unlike qwebkit, qwebengine loads and displays its content asynchronously. Most application are using it to load network based files .We inject our content directly and are therefore are using it differently that most other applications. My first thought about this is that it is a Qt bug. I will continue to look into it.

**Comment by mgruner** [comment] 2016-04-21 19:47
Hello Gary,

so far I have not seen problems because of this, but I also haven’t done detailed testing.

Best regards, Martin

**Comment by Geremia** [comment] 2016-10-08 17:25
I get several variants of these JavaScript errors with 2.11.0_rc2:

When hovering over the OSHB Hebrew scripture text:
>`WARNING: javascript console : "Uncaught TypeError: btHtmlJsObject.mouseMoveEvent is not a function"`

When hovering over the ABPGRK Greek scripture text, I get (in addition to the above error):
>`WARNING: javascript console : "Uncaught ReferenceError: qt is not defined"`

Both these errors prevent anything from showing up in the Mag viewer.

**Comment by gholmlund** [comment] 2016-10-08 18:45
I have seen times in the past where the Mag viewer was not working. Please try the following.
1. Verify you have installed the Hebrew and Greek lexicons (such as StrongsGreek and StrongsHebrew).
2. Open Settings > Configure BibleTime, Desk
3. Verify you have the above lexicons showing in Hebrew Strong,s lexicon and Greek Strong's lexicon.
4. Press the Ok button even if you did not change anything.
5. close and restart BibleTime.
At this point I do see some javascript warnings but my Mag window is working.
I have seen this in the past be have not been able to figure the issue out. It seems like something wrong when settings have not previously been saved.

**Comment by Geremia** [comment] 2016-10-09 03:09
@gholmlund 
> At this point I do see some javascript warnings but my Mag window is working.
The Mag viewer works now, but it stops updating when I change the book, verse, or chapter. That's when the above JavaScript errors start cropping up, too.

**Comment by gholmlund** [comment] 2016-10-12 21:46
In observing BibleTime with Qt 5.7, I see a javascript error, WARNING: javascript console : "Uncaught ReferenceError: qt is not defined". After this occurs numerous javascript errors appear. These error come from the MAG window as the mouse moves into and around in it. They do not appear to stop the MAG window from being updated by mouse movement in other windows. 

I have found that Qt 5.7 has a regression from Qt 5.6.
https://bugreports.qt.io/browse/QTBUG-52209
http://stackoverflow.com/questions/38394130/qwebengine-qwebchannel-transport-object-qt-webchanneltransport-disappeared
This problem has been fixed in the unreleased Qt 5.7.1.

It is unclear if we can do anything to fix this, but I am continuing to look at it. Also, I repeat that I have not found it is causing any problem.

**Comment by Geremia** [comment] 2016-10-12 23:01
@gholmlund I get the JavaScript problems when hovering over the scriptures window or the Mag view. I'm using Qt 5.7.0.

**Comment by gholmlund** [comment] 2016-10-28 19:28
Javascript Error Testing

Ensure KJV, ESV, StrongsGreek, and StrongsHebrew are installed. The config dialog was used to set the Hebrew/Greek Strong's lexicons. Testing is done by hovering over KJV words, ESV references, the MAG Window, and the Bookshelf window module names and observing the MAG window and application output (with --debug option).

NOTE: Qt 5.6 and later are using QtWebEngine.

After testing with several versions of Qt, here is the status of javascript errors:

Qt 5.5.1 - QtWebEngine not used. No javascript errors and the MAG window seems to work fine.

Qt 5.6.1,5.6.2 - Javascript  warnings like this occur. "Uncaught TypeError: Cannot read property 'addEventListener' of undefined". The MAG window continues to work correctly.

Qt 5.7.0 - Numerous warnings like this occur. 
        "Uncaught ReferenceError: qt is not defined". 
    The MAG window continues to work. 
    Also errors like this occur when hovering over the MAG window.         
        "Uncaught TypeError: btHtmlJsObject.mouseMoveEvent is not a function"

Qt 5.7.1 snapshot 551 - No javascript errors were found and MAG functionality is working correctly.

I have studied the call stacks where these javascript errors occur. I believe they are all Qt issues and that BibleTime cannot do anything to eliminate them. I note that Qt seems to have finally got it right with the 5.7.1 version. 

They do not seem to affect the MAG window functionality. I am closing this issue.

**Closed by gholmlund** 2016-10-28 19:28 UTC
Labels: component: Qt related, type: BUG
