### ISSUE TITLE
Clicking on the Setup button in the Search dialog box crashes the app

### ISSUE THREAD

**Issue by entodoays** [bibletime/bibletime#224] opened 2020-03-06 09:42 UTC
Using the snap version of version 3.0.0 beta2 on Ubuntu 19.10 on a Wayland session here.

If I open the Search dialog and click the setup button the app segfaults.

**Comment by gholmlund** [comment] 2020-03-07 15:41
I have tried to reproduce this problem using ubuntu 19.10 (x11 and wayland) and kubuntu (x11 and wayland). I have not been able to reproduce it.

**Comment by entodoays** [comment] 2020-03-07 19:37
See attachment just before clicking the setup button in dialog box.

**Comment by gholmlund** [comment] 2020-03-08 01:21
I don't see an attachment. You probably attached to a reply email, but you should go to the github issue to attach a file.

**Comment by entodoays** [comment] 2020-03-10 10:25
I uploaded the screenshot in the comment above.

**Comment by gholmlund** [comment] 2020-03-10 14:46
Thanks fore the picture. I am still unable to reproduce this by making my window look like your picture.

**Comment by entodoays** [comment] 2020-03-10 21:34
Is there a way to view logs? Would sending the list of modules I have installed help?

10 Mar 2020 15:46:15 gholmlund <notifications@github.com>:

**Comment by gholmlund** [comment] 2020-03-11 02:03
We have a debug output that logs some activity, but I checked it and it does not deal with search settings. I don't have a further recommendation about debugging this.

**Comment by entodoays** [comment] 2020-03-12 08:38
I don't have flatpak installed on my PC and would rather not install yet another packaging system.

**Comment by jaakristioja** [comment] 2020-05-08 22:30
I'm unable to reproduce this with Ubuntu 19.10 on X11. On Ubuntu 19.10 with Wayland, the BibleTime GUI seems to hang indefinitely when trying to open/display the CPDV module.

**Comment by jaakristioja** [comment] 2020-05-17 20:50
I believe this to be an issue with the system (Ubuntu) or Qt, rather than a bug in the code of BibleTime. And because the BibleTime project is currently quite shorthanded, we do not have the resources to track down the exact reasons for this.

Note that Wayland platforms still have many issues and are not as stable as Xorg. You could retry with [BibleTime 3.0 RC 1](https://github.com/bibletime/bibletime/releases/tag/v3.0_rc1). If that does not work, I suggest switching to Ubuntu 20.04, as it might have better Wayland support and Canonical will probably end standard support for Ubuntu 19.10 in July.

Closing. Please reopen if this nevertheless turns out to be a bug in our code.

**Closed by jaakristioja** 2020-05-17 20:50 UTC
Labels: type: BUG

**Comment by entodoays** [comment] 2020-05-18 08:00
I upgraded to Ubuntu 20.04, ran the snap version of Bibletime 3.0 RC1 on an Xorg session and am still getting this bug.
When running from a terminal I get `Qt: Session management error: None of the authentication protocols specified are supported` on opening and `Segmentation fault (core dumped)` when pressing the setup button in the search dialog box.

**Comment by gholmlund** [comment] 2020-05-18 14:33
I found and fixed a crash when pushing the setup button of the search dialog. It is possible it is not the same bug as reported. I have updated the snap to have that change. Please test it.

**Comment by entodoays** [comment] 2020-05-18 15:22
I tested it and the problem is solved.
