### ISSUE TITLE
[BUG] archive.sh: exit trap single and double quotes are switched

### ISSUE THREAD

**Issue by wileyhy** [bibletime/bibletime#437] opened 2023-07-20 06:10 UTC
**Bug description**
Some quotes are incorrect on the exit trap in archive.sh. When the entire args section of the trap definition is enclosed in double quotes, any variables would be expanded when the trap is defined, rather than when the trap executes. 

```sh
[liveuser@localhost-live test]$ cat ./test_wrong.sh 
#!/bin/sh -x
ls -a
foo=quux
trap "command rm -rf '${foo}'" EXIT
trap -p 0
foo=hoge
mkdir "$foo"
touch "${foo}/bar"
exit 0

[liveuser@localhost-live test]$ diff -u ./test_wrong.sh ./test_right.sh 
--- ./test_wrong.sh	2023-07-19 23:00:56.202193096 -0700
+++ ./test_right.sh	2023-07-19 23:01:20.985194994 -0700
@@ -1,7 +1,7 @@
 #!/bin/sh -x
 ls -a
 foo=quux
-trap "command rm -rf '${foo}'" EXIT
+trap 'command rm -rf "${foo}"' EXIT
 trap -p 0
 foo=hoge
 mkdir "$foo"

[liveuser@localhost-live test]$ ./test_wrong.sh 
+ ls -a
.  ..  test_right.sh  test_wrong.sh
+ foo=quux
+ trap 'command rm -rf '\''quux'\''' EXIT
+ trap -p 0
trap -- 'command rm -rf '\''quux'\''' EXIT
+ foo=hoge
+ mkdir hoge
+ touch hoge/bar
+ exit 0
+ command rm -rf quux
[liveuser@localhost-live test]$ ls -a
.  ..  hoge  test_right.sh  test_wrong.sh
[liveuser@localhost-live test]$ rm -fr ./hoge/
[liveuser@localhost-live test]$ ./test_right.sh
+ ls -a
.  ..  test_right.sh  test_wrong.sh
+ foo=quux
+ trap 'command rm -rf "${foo}"' EXIT
+ trap -p 0
trap -- 'command rm -rf "${foo}"' EXIT
+ foo=hoge
+ mkdir hoge
+ touch hoge/bar
+ exit 0
+ command rm -rf hoge
[liveuser@localhost-live test]$ ls -a
.  ..  test_right.sh  test_wrong.sh
[liveuser@localhost-live test]$ 
```

**System information:**
 - OS and OS version: Fedora 38
  - BibleTime Version: NA -- found via Google
 - How BibleTime was installed: NA

**Comment by jaakristioja** [comment] 2023-07-21 11:02
The variable `$TMPDIR` is meant to be expanded when the trap is defined. This is also why it has the `# shellcheck disable=SC2064` annotation to silence [shellcheck](https://www.shellcheck.net/). We set the trap immediately after creating the `$TMPDIR` directory and want to expand it right there, lest the `$TMPDIR` variable is changed later. Also, the Bash documentation does not seem to give guarantees about the environment the trap argument is executed in, so during execution of the trap the `$TMPDIR` variable might (in theory) expand to something else entirely. So even using `declare -r TMPDIR` to mark `TMPDIR` read-only might not mitigate this risk.

I think the only risk from expanding `$TMPDIR` during the trap definition is from `mktemp -d` returning a value containing single quotes, but I don't think any sane distribution of `mktemp` would allow that unless the environment to `mktemp` already contains `TMPDIR` variable with single quotes. However, this is also quite unlikely.

Therefore I think it is safer to expand `$TMPDIR` right there, and the change of quotes might instead make things worse.

Currently closing this as INVALID. If you think the current behavior is still incorrect, please reopen with an explanation.

**Closed by jaakristioja** 2023-07-21 11:02 UTC
Labels: type: BUG

**Comment by jaakristioja** [comment] 2023-07-21 11:55
> I think the only risk from expanding `$TMPDIR` during the trap definition is from `mktemp -d` returning a value containing single quotes, but I don't think any sane distribution of `mktemp` would allow that unless the environment to `mktemp` already contains `TMPDIR` variable with single quotes. However, this is also quite unlikely.

This is now mitigated by commit 7e9ddd30678b53d40812fabef9eae061dee08541.

**Comment by wileyhy** [comment] 2023-07-22 05:24
Hmm... ....so for you, concern 1 is, "could TMPDIR be redefined later, and how would that happen?" 

A memory bug; it's pretty rare, but it happens. One important thing to remember is that other processes cannot alter the environment of a running bash process. [Here](http://mywiki.wooledge.org/Environment) is a page with some pretty good explanations, although the summary at the top of the page is pretty poorly worded.... Under normal operation, ie, absent root access with a debugger, other processes simply cannot alter a script's environment. Once a script has begun execution, not even its parent process can alter its environment. 

Concern 2 : "could `readonly` fail to prevent TMPDIR from expanding to anything other than its intended value?" 

Within the context of these 39 lines of shell code, I believe the answer to this question is, "no." The relevant behavior of [export](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#export), [readonly](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#readonly) and [unset](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#unset) is defined by POSIX, and bash's definitions are [very](https://www.gnu.org/software/bash/manual/bash.html#index-export) [very](https://www.gnu.org/software/bash/manual/bash.html#index-readonly) [similar](https://www.gnu.org/software/bash/manual/bash.html#index-unset) as a superset of POSIX's definitions. Attempting to assign a value to a read-only variable is an error and would trigger errexit. 

Concern 3, "what if the output of `mktemp` contains single quotes?"

It sounds like you may already aware that `mktemp` depends on the value of TMPDIR.  Double quoting variable expansions is the correct way to handle such strings, as it preserves the non-special values of all non-[[:alnum:]] ASCII characters, however, UTF-8 conversion issues are something else. The [Quoting](https://www.gnu.org/software/bash/manual/bash.html#Double-Quotes) section of the GNU manual goes into some detail on that.  

Unfortunately, the as test written into commit 7e9ddd3 will always fail. 

```sh
 $ unset -v x
 $ unset -f x
 $ unset -n x
 $ declare -p x
bash: declare: x: not found
 $ set -x ; ! true "${x@K}" ; echo $? ; set -
+ true ''
+ echo 1
1
+ set -
 $ x=y
 $ declare -p x
declare -- x="y"
 $ set -x ; ! true "${x@K}" ; echo $? ; set -
+ true ''\''y'\'''
+ echo 1
1
+ set -
 $ 
```

${foo@K} was created in [version](http://mywiki.wooledge.org/BashFAQ/061) 5.1, so that would exclude any older Apple machines that have as their default shell some version of bash 2, and the ${foo@K} pattern isn't present in the zshall(1) man page, from what I could see ( `man -s1 --n{h,j} zshall | grep -F -- '@K'` ), but maybe the script will never run on a Mac, so then it wouldn't matter. '${foo@K}' is defined in `man bash` as producing a "_possibly-quoted_ version of the value of parameter." Unfortunately, while `man bash` is intended to be the "authoritative" definition of bash's behaviour, it really isn't known for listing out exceptions exhaustively. For example, definitions of functions are omitted from xtrace output, and neither `export` nor `export -n` can export name references as `declare -nx VAR` does. 

Lastly, I think it's possibly that assigning to TMPDIR with `mktemp` could possibly lead to a race condition within `mktemp` as the program reads to and writes from the same variable. While I haven't seen any evidence of that, I think it's within the realm of possibility. 

And hey, thanks for letting people post bug reports. :-)

**Comment by jaakristioja** [comment] 2023-07-22 20:12
> Hmm... ....so for you, concern 1 is, "could TMPDIR be redefined later, and how would that happen?"
> 
> A memory bug; it's pretty rare, but it happens. One important thing to remember is that other processes cannot alter the environment of a running bash process. [Here](http://mywiki.wooledge.org/Environment) is a page with some pretty good explanations, although the summary at the top of the page is a little poorly worded.... Under normal operation, ie, absent root access with a debugger, other processes simply cannot alter a script's environment. Once a script has begun execution, not even its parent process can alter its environment.

The concern was instead that in the future, a programmer (perhaps even myself) might inadvertently redefine TMPDIR.

> Concern 2 : "could `readonly` fail to prevent TMPDIR from expanding to anything other than its intended value?"
> 
> Within the context of these 39 lines of shell code, I believe the answer to this question is, "no." The relevant behavior of [export](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#export), [readonly](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#readonly) and [unset](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#unset) is defined by POSIX, and bash's definitions are [very](https://www.gnu.org/software/bash/manual/bash.html#index-export) [very](https://www.gnu.org/software/bash/manual/bash.html#index-readonly) [similar](https://www.gnu.org/software/bash/manual/bash.html#index-unset) as a superset of POSIX's definitions. Attempting to assign a value to a read-only variable is an error and would trigger 'errexit.'

No. The concern was that the environment during the execution of the trap might differ from the environment of the script.

> Concern 3, "what if the output of `mktemp` contains single quotes?"
> 
> It sounds like you may already be aware of how `mktemp` can depend upon the value of TMPDIR, as do `sort`, `patch`, and `ssh-agent` among others ( `man -K TMPDIR` ). Double quoting variable expansions is the correct way to handle such strings, as it preserves the non-special values of most non-[[:alnum:]] ASCII characters, except, in non-POSIX bash, '$', "`", '' and '!', however, UTF-8 conversion issues are something else. The [Quoting](https://www.gnu.org/software/bash/manual/bash.html#Double-Quotes) section of the GNU manual goes into some detail on that.

Yes, this was a separate concern not directly related to this issue. However, I still think that we should expand `TMPDIR` while defining the trap, and for this the `@K` parameter transformation works best, as we don't need to manually write error-prone code to sanitize the values.

> Unfortunately, the as test written into commit [7e9ddd3](https://github.com/bibletime/bibletime/commit/7e9ddd30678b53d40812fabef9eae061dee08541) will always fail.
> 
> ```shell
>  $ unset -v x
>  $ unset -f x
>  $ unset -n x
>  $ declare -p x
> bash: declare: x: not found
>  $ set -x ; ! true "${x@K}" ; echo $? ; set -
> + true ''
> + echo 1
> 1
> + set -
>  $ x=y
>  $ declare -p x
> declare -- x="y"
>  $ set -x ; ! true "${x@K}" ; echo $? ; set -
> + true ''\''y'\'''
> + echo 1
> 1
> + set -
>  $ 
> ```

I did not not fully analyze your demo code, as the `archive.sh` script itself seems to work pretty well for me.

> ${foo@K} was created in [version](http://mywiki.wooledge.org/BashFAQ/061) 5.1, so that would exclude any older Apple machines that have as their default shell some version of bash 2, and the ${foo@K} pattern isn't present in the zshall(1) man page, from what I could see ( `man -s1 --n{h,j} zshall | grep -F -- '@K'` ), but maybe the script will never run on a Mac, so then it wouldn't matter. '${foo@K}' is defined in `man bash` as producing a "_possibly-quoted_ version of the value of parameter." Unfortunately, while `man bash` is intended to be the "authoritative" definition of bash's behaviour, it really isn't known for listing out exceptions exhaustively. For example, definitions of functions are omitted from xtrace output, and neither `export` nor `export -n` can export name references as `declare -nx VAR` does.

The `archive.sh` script is only used for release procedures, so compatibility with other shells and older versions of Bash is not a priority.

> Lastly, I think it's possible that assigning to TMPDIR with `mktemp` could possibly lead to a race condition within `mktemp` as the program reads to and writes from the same variable. While I haven't seen any evidence of that, I think it's within the realm of possibility.

I don't think that is possible. As you stated yourself, the parent process (`archive.sh`) can not modify the environment of the child process (`mktemp`) after creation. The assignment to `TMPDIR` in `archive.sh` happens after `mktemp` exits.

> And hey, thanks for letting people post bug reports. :-)

You're welcome. Although I did not integrate your changes, I believe this helped us make things slightly better. Thank you for taking the time! :-)

**Comment by wileyhy** [comment] 2023-07-22 23:09
Jaak,
  Well, I hope you'll reconsider reading through this CLI / XTrace log. It
really is quite straightforward.  I'm sorry for being the bearer of bad
news.
  Thanks,
  Wiley

**Comment by jaakristioja** [comment] 2023-07-24 23:13
@wileyhy Fair enough. But afaict, the log you pasted does not correspond to what the `archive.sh` script does exactly, because you did not use `set -u`. The `set -u` is why I think `archive.sh` still works as intended. However, I'm still open to reconsider my position, so feel free to prove me wrong. :-)
