### ISSUE TITLE
[ENHANCEMENT] Package BibleTime as Appimage

### ISSUE THREAD

**Issue by JohnStaf** [bibletime/bibletime#333] opened 2021-08-01 13:18 UTC
Congratulations on a new release! I very much appreciate your work. I work in Linux though a relative novice. Building from source is a little beyond me. I write to ask if an AppImage can be constructed - simple for Linux users.
Best wishes.

**Comment by jaakristioja** [comment] 2021-08-01 15:35
Duplicate of #220 (or perhaps even #293). Closing.

**Closed by jaakristioja** 2021-08-01 15:35 UTC
Labels: type: ENHANCEMENT
