### ISSUE TITLE
Bibletime fails to start because it can't store user settings under "C:/Program Files (x86)/BibleTime"

### ISSUE THREAD

**Issue by andrew-ivanov** [bibletime/bibletime#116] opened 2017-09-23 13:31 UTC
Steps executed:
1. Uninstalled previous version of Bibletime
2. Downloaded, verified and installed latest version released (BibleTime-2.11.0-win32.exe)
3. Clicked the Bibletime item in the start menu
**Observed:**
Bibletime did not start. Nothing visible happened. Task manager does not list a bibletime process.

4. Tried starting bibletime.exe from command line
**Observed:**
Bibletime did start. 
Careful inspection of the shortcut put in the Start Menu by the installer revealed that it sets the working directory to _"C:/Program Files (x86)/BibleTime"_. Trying to start the the program from that directory in debug mode produced the bellow listed log. Changing the shortcut's working directory to _"%USERPROFILE%"_ allowed the shortcut to start the program.

**BibleTime Debug.txt**
> (BibleTime 2.11.0+52ef4a4d7f0d0902a0d90d6ef60c07da70b89ef7) WARNING: Could not create user settings directory relative to "C:/Program Files (x86)/BibleTime"
> (BibleTime 2.11.0+52ef4a4d7f0d0902a0d90d6ef60c07da70b89ef7) FATAL: Error initializing directory cache!
> Please report this bug at https://github.com/bibletime/bibletime/issues

Please note that the above issue has been observed on a Windows 10 x64 machine with Bulgarian locale and user named in Cyrillic i.e. the path to the %USERPROFILE% contains Cyrillic letters. The previously running version of Bibletime was [a dev build of 2.11.0 RC provided by gholmlund in response to issue #80](https://github.com/bibletime/bibletime/issues/80#issuecomment-261813339). 

The observed behavior sounds similar to the one [described by treestryder in the linked bug](https://github.com/bibletime/bibletime/issues/80#issuecomment-298461122) however I could not find any related issue (open or otherwise) after a quick search.

Please let me know if I can provide any further assistance.

**Comment by gholmlund** [comment] 2018-02-04 04:04
@andrew-ivanov 
After studying the code, it seems that that your environment variable, %AppData%, is wrong. Please run the following command from a command prompt window:
echo %AppData%

It should look something like this.
C:\Users\<name>\AppData\Roaming

**Comment by andrew-ivanov** [comment] 2018-02-08 13:13
@gholmlund

Here's the output of the command you recreated:

C:\Users\ЕПЦ Перник>echo %AppData%
C:\Users\ЕПЦ Перник\AppData\Roaming

C:\Users\ЕПЦ Перник>

**Comment by gholmlund** [comment] 2018-02-08 20:41
I thought it may relate to the character set in your name, but after creating an account with that name I still cannot reproduce this. 

Have you tried the latest BibleTime for Windows. 
https://github.com/bibletime/bibletime/releases
There are 2 versions for Windows. The latest has an extra "-2" in the name. It uses the latest sword 1.8.1 name.

**Comment by andrew-ivanov** [comment] 2018-02-09 20:31
Today I downloaded and installed BibleTime-2.11.1-2-win32
This version did not exhibit the above described behavior.

---
Your email is important for us
The World Spy Consortium

2018-02-08 22:41 GMT+02:00 gholmlund <notifications@github.com>:

**Comment by gholmlund** [comment] 2018-02-09 22:03
Duplicate of bug #90.

**Closed by gholmlund** 2018-02-09 22:03 UTC
Labels: resolution: DUPLICATE, type: BUG
