### ISSUE TITLE
Bug - Bible not updating when switching chapter

### ISSUE THREAD

**Issue by drduker** [bibletime/bibletime#169] opened 2018-12-20 13:00 UTC
Bug - Bible not updating when switching chapter

I've noticed several times that the chapter or anything else in the bible resource isn't updating after adding and removing "Show scripture cross-references".

Symptom: the text of where it last is working doesn't move.  

Work around:  Close the resource and reopen it usually fixes it.

Environment:
2.11.12 -bibletime version
macos 10.14.1
macbook pro 15in 2017

Side note: how could I debug this myself while it is running live?  I would like to see what is happening in the code.  This way I could provide more helpful/detailed feedback.  Thanks!

**Comment by gholmlund** [comment] 2019-04-10 00:56
I cannot reproduce this on my macos 10.14.

**Comment by gholmlund** [comment] 2019-07-23 22:39
Closing as not reproducible.

**Closed by gholmlund** 2019-07-23 22:39 UTC
Labels: type: BUG
