### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by cscj001** [bibletime/bibletime#419] opened 2022-12-05 20:38 UTC
**Bug description**

Using Ubuntu 22.04.1, Bibletime would not start from Desktop icon.  Started it from terminal and received the following message:

`bibletime`
>(BibleTime 3.0.2) FATAL: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Please report this bug at https://github.com/bibletime/bibletime/issues
Aborted (core dumped)

**Steps to reproduce**

1. Type bibletime in terminal

**Expected behavior**

I expected Bibletime to open normally.

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**System information:**
Ubuntu 22.04.1
bibletime 3.0.2

**Additional context**

Initial logo appears before the abort.

**Comment by rambo919** [comment] 2023-01-22 06:43
Using Bibletime 3.0.3 this happened to me now too.... the odd thing is it was working fine but when it finished downloading new books it crashed and now wont start up again.

**Comment by rambo919** [comment] 2023-01-22 08:19
OK this is weird.

Looking at .sword I noticed only a few conf files were altered today.... so I moved them out and the program started.

Moving them back in in batches had the program start fine.... even after all of them were moved back in.

This kind of behavior might explain why people might find this bug difficult to reproduce..... something wrong with garbage collection or something maybe?

**Comment by cscj001** [comment] 2023-01-22 21:54
I installed Xiphos because I could not get Bibletime to start.  Then I had a system update (don't remember the software that was affected) that required a restart.  After the restart, Bibletime began working again.  I still have Bibletime 3.0.2 but Linux kernel is now 5.15.0-58-generic.  So I don't know if it was the restart itself that cleared up something, or some upgraded software.  In any case, I am glad Bibletime is working because I do not care for the way Xiphos works.

**Comment by gholmlund** [comment] 2023-06-27 00:41
Since we don't know how to reproduce this and cscj001 does not have the problem and longer, I will close this.

**Closed by gholmlund** 2023-06-27 00:41 UTC
Labels: type: BUG

**Comment by jaakristioja** [comment] 2023-10-31 16:18
This also duplicates #125, #170, #176 and #295.
