### ISSUE TITLE
Search keywords

### ISSUE THREAD

**Issue by squarehimself** [bibletime/bibletime#47] opened 2015-12-02 01:00 UTC
Not really an issue, but what css element would I need to style in order to change the background color for the words that are highlighted when you search for them? The yellow is unreadable for me, as you can see here: http://i.imgur.com/zTnqFLi.png

**Comment by JudahsShadow** [comment] 2015-12-02 02:42
What style do you have selected? I'm pretty familiar with most, if not all, of the style sheets (I made some of them) so I could probably figure it out.

On December 1, 2015 8:00:14 PM EST, Square <notifications@github.com> wrote:
>Not really an issue, but what css element would I need to style in
>order to change the background color for the words that are highlighted
>when you search for them? The yellow is unreadable for me, as you can
>see here: http://i.imgur.com/zTnqFLi.png
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/bibletime/bibletime/issues/47

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by squarehimself** [comment] 2015-12-02 06:16
I modified one of the existing stylesheets. I was not able to find any
examples amongst the others where the color I'm looking to change is
affected.

**Comment by jaakristioja** [comment] 2016-07-19 12:58
The colour was hard-coded. Should be fixed by https://github.com/bibletime/bibletime/commit/626c14f59d53f6992a25aa01579566c5b60cb79b. Duplicate of https://github.com/bibletime/bibletime/issues/62.

**Closed by jaakristioja** 2016-07-19 12:58 UTC
Labels: question
