### ISSUE TITLE
Mag window always blank

### ISSUE THREAD

**Issue by 3lti** [bibletime/bibletime#14] opened 2014-09-18 15:00 UTC
My mag windows stays blank whatever I do.  Nothing appears when I mouse over KJV & others.  Worked fine last time I used Bibletime.  Didn't change anything.  I've selected different lexicons under "Configure Bibletime"...nothing.  Last time I had to reinstall everything.  Now it's quit again.  Ditto for the Bookshelf window.

**Comment by kalemas** [comment] 2015-09-09 12:38
It have to change anyway even you have no corresponding module to decode it.
Does it still reproduceable?
You platform and build type?

**Comment by jaakristioja** [comment] 2016-10-05 13:36
Closing due to timeout. Reopen if needed.

**Closed by jaakristioja** 2016-10-05 13:36 UTC
Labels: bug, need more info
