### ISSUE TITLE
[BUG] Unexpected Selection/Copy behavior when selecting off the currently viewed page (scrolling)

### ISSUE THREAD

**Issue by ma77carpenter** [bibletime/bibletime#415] opened 2022-10-21 17:42 UTC
**Bug description**
When attempting to select verses for copying, if the selection requires scrolling past the currently viewed verses, the resulting selection is unexpectedly less than what you want.

**Steps to reproduce**
1. Open any Bible (engKJV2006eb is what I'm currently looking at)
2. Open any Book/Chapter (Revelation 1 is what I'm looking at)
3. Hold down the mouse left button to start select at any appropriate verse portion (keep track where, for comparison) 
4. Drag up or down (either way displays the bug) and let the selection scroll off the currently viewed page... ie.  the start of your selection should no longer be visible to you.
5. Ctrl-C (or Copy, however you like)  and Paste into an editor of your choosing (Vim for me right now)
6. Compare what you should have copied to what actually was pasted.

**Expected behavior**
I expect to be able to select Bible text the same way I always have in previous versions of BibleTime and other text-based apps:  I place the start of selection at one location, I scroll to another location, and when I let up on the mouse button, I expect all the text between the starting point and where I stopped to be selected for copy.

**Screenshots**
If applicable, please add screenshots to help explain your problem.

Beginning copy:
![Screenshot_20221021_124336](https://user-images.githubusercontent.com/19736851/197247427-62496678-38a5-4288-ad01-f37c07f5eb9d.png)

Ending copy (see the odd artifacts near the "earlier" parts of the copy):
![Screenshot_20221021_124350](https://user-images.githubusercontent.com/19736851/197255605-ee12c94b-e6ca-44fb-b450-e935f1ff1976.png)

Resulting paste:
![Screenshot_20221021_124514](https://user-images.githubusercontent.com/19736851/197255636-d21de4b7-899a-4aa0-99df-46e5d8e120aa.png)

**System information:**
 - Kubuntu 22.04.01
 - BibleTime Version 3.0.3 (via Snap).  Same issue seen in 3.0.2-1 (via Apt).  Same issues seen on a different system, Kubuntu 21.10 running BibleTime v3.0.0
 - How BibleTime was installed Ubuntu Snap as well as Apt

**Additional context**
Nothing worth including here.  It may be worth noting that this is an install

**Comment by careimer** [comment] 2022-11-09 16:36
Same problem on Debian 11 bibletime v3.0.3-1 installed via apt from bookworm repo.

**Comment by jaakristioja** [comment] 2022-12-04 12:02
@gholmlund I've also had such issues and these seem to be related to the QML text selection logic. Could please also take a look at this?

**Comment by jaakristioja** [comment] 2022-12-04 19:03
Assigned myself as well, because I've already started refactoring this logic in the master branch.

**Comment by jaakristioja** [comment] 2022-12-30 17:51
I rewrote the text selection code in a717ce7db531bb3825b005e914a4b7c35148d39a in the master branch, which I hope fixes this issue. Please test, if you can.

It might be difficult to backport this to the 3.0 series of BibleTime. I'm leaning towards not releasing a 3.0.4 bugfix release and instead focusing on BibleTime 3.1, but since I have not yet made a decision in this matter, I'm keeping this issue open for now.

**Comment by gholmlund** [comment] 2022-12-30 21:08
I did some testing including scrolling off screen and using multiple columns. It looked correct.

**Comment by gholmlund** [comment] 2023-07-11 16:26
I did further testing in 3.0.3 and can easily reproduce this. I tried the master branch and cannot reproduce it.
I am closing as fixed.

**Closed by gholmlund** 2023-07-11 16:26 UTC
Labels: type: BUG, component: Frontend
