### ISSUE TITLE
[FEEDBACK] Too lot of tags in text in BT GUI translation

### ISSUE THREAD

**Issue by ilkant** [bibletime/bibletime#393] opened 2022-05-30 00:20 UTC
There were some new phrases to translate. They are difficult to translate, because there are lot of tags. And in finnish language for example the words in sentence are in different order than original text.

441
Now there was a man of the Pharisees, named John 7:50;19:39 Nicodemus, a Luke 23:13; John 7:26,48 ruler of the Jews;

442
this man came to Jesus by night and said to Him, "Matt 23:7; John 3:26 Rabbi,we know that You have come from God as a teacher; for no one can do these (1)John 2:11 signs that You do unless John 9:33;10:38;14:10f;Acts 2:22;10:38 God is with him."

**Comment by jaakristioja** [comment] 2022-06-05 15:40
We know. The translatable strings in `CDisplaySettingsPage::updateStylePreview()` contain a lot of tags by design, and I don't think there is a better way to do it without the tags, because these texts are specifically meant to be displayed for a short preview containing many features. A better preview greatly improves the user experience for changing the display theme. See #306 for details.

Context: https://github.com/bibletime/bibletime/blob/de33b613f3b63ade9831fc9db7ac3f9b217366e0/src/frontend/settingsdialogs/cdisplaysettings.cpp#L208-L314

**Comment by jaakristioja** [comment] 2022-06-05 19:03
The tags will probably stay, but I'll try to improve the situation for translators a bit.

**Comment by jaakristioja** [comment] 2022-06-05 20:09
I just committed a20c618a1ff58bfeca59772dca43e083276c5dc6 to hopefully make it a bit easier for translators in the future. The `CDisplaySettingsPage::updateStylePreview()` function now looks like this: https://github.com/bibletime/bibletime/blob/a20c618a1ff58bfeca59772dca43e083276c5dc6/src/frontend/settingsdialogs/cdisplaysettings.cpp#L225-L357

@ilkant Thank you for bringing this topic to our attention! :smiley:

**Closed by jaakristioja** 2022-06-05 20:09 UTC
Labels: component: Translations, type: Feedback, component: Frontend
