### ISSUE TITLE
Bibletime fails to start in Ubuntu 22.04.4

### ISSUE THREAD

**Issue by cscj001** [bibletime/bibletime#454] opened 2024-03-03 19:42 UTC
**Bug description**
After failing to start from my menu, I entered the required command in a terminal  Here is the result:

bibletime
(BibleTime 3.0.2) FATAL: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Please report this bug at https://github.com/bibletime/bibletime/issues
Aborted (core dumped)

I also checked syslog for any pertinent results.  Here is that information:

Mar  3 14:13:14 cp1 metacity[3020]: Invalid WM_TRANSIENT_FOR window 0x4a00008 specified for 0x4a00009 (bibletime).
Mar  3 14:13:14 cp1 kernel: [4408648.142497] NVRM: API mismatch: the client has the version 470.239.06, but
Mar  3 14:13:14 cp1 kernel: [4408648.142497] NVRM: this kernel module has the version 470.223.02.  Please
Mar  3 14:13:14 cp1 kernel: [4408648.142497] NVRM: make sure that this kernel module and all NVIDIA driver
Mar  3 14:13:14 cp1 kernel: [4408648.142497] NVRM: components have the same version.
Mar  3 14:13:15 cp1 kernel: [4408648.159802] NVRM: API mismatch: the client has the version 470.239.06, but
Mar  3 14:13:15 cp1 kernel: [4408648.159802] NVRM: this kernel module has the version 470.223.02.  Please
Mar  3 14:13:15 cp1 kernel: [4408648.159802] NVRM: make sure that this kernel module and all NVIDIA driver
Mar  3 14:13:15 cp1 kernel: [4408648.159802] NVRM: components have the same version.
Mar  3 14:13:15 cp1 kernel: [4408648.177464] NVRM: API mismatch: the client has the version 470.239.06, but
Mar  3 14:13:15 cp1 kernel: [4408648.177464] NVRM: this kernel module has the version 470.223.02.  Please
Mar  3 14:13:15 cp1 kernel: [4408648.177464] NVRM: make sure that this kernel module and all NVIDIA driver
Mar  3 14:13:15 cp1 kernel: [4408648.177464] NVRM: components have the same version.
Mar  3 14:13:15 cp1 kernel: [4408648.193115] NVRM: API mismatch: the client has the version 470.239.06, but
Mar  3 14:13:15 cp1 kernel: [4408648.193115] NVRM: this kernel module has the version 470.223.02.  Please
Mar  3 14:13:15 cp1 kernel: [4408648.193115] NVRM: make sure that this kernel module and all NVIDIA driver
Mar  3 14:13:15 cp1 kernel: [4408648.193115] NVRM: components have the same version.

**Steps to reproduce**
1. Enter bibletime in terminal or launch from menu (same results)
2. See error

**Expected behavior**

Bibletime opens with last layout of open Bible(s) and/or Commentaries.

**Screenshots**
If applicable, please add screenshots to help explain your problem.

**System information:**
 - Ubuntu 22.04.4 x64
 - BibleTime Version 3.0.2-1
 - How BibleTime was installed - Bibletime was installed from system packages
 - Versions of modules related to the crash (if known)
 - (If compiled from source) Sword Version
 - (If compiled from source) Qt Version

**Additional context**
Add any other context about the problem here, e.g. including output of `bibletime --debug` and/or backtraces in case of crashes.

bibletime--debug

bibletime --debug
LOOKING UP LOCALE DIRECTORY...
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Checking working directory for mods.conf...
Checking working directory for mods.d...
Checking working directory ../library/ for mods.d...
Checking $SWORD_PATH...
Parsing /etc/sword.conf...
Checking for /etc/sword.conf...
found.
DataPath in /etc/sword.conf is set to /usr/share/sword/.
Checking for mods.conf in DataPath...
Checking for mods.d in DataPath...
found.
LOOKING UP LOCALE DIRECTORY COMPLETE.
LocaleMgr::loadConfigDir loading /usr/share/sword/locales.d
LOOKING UP MODULE CONFIGURATION...
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Checking working directory for mods.conf...
Checking working directory for mods.d...
Checking working directory ../library/ for mods.d...
Checking $SWORD_PATH...
Parsing /etc/sword.conf...
Checking for /etc/sword.conf...
found.
DataPath in /etc/sword.conf is set to /usr/share/sword/.
Checking for mods.conf in DataPath...
Checking for mods.d in DataPath...
found.
LOOKING UP MODULE CONFIGURATION COMPLETE.
LOADING MODULE CONFIGURATIONS...
LOADING MODULE CONFIGURATIONS COMPLETE.
LOADING MODULE LIBRARY...
libsword: SWMgr::createAllModules
libsword: SWMgr::createAllModules
LOADING MODULE LIBRARY COMPLETE.
(BibleTime 3.0.2) FATAL: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Please report this bug at https://github.com/bibletime/bibletime/issues
Aborted (core dumped)

**Comment by jaakristioja** [comment] 2024-03-03 20:12
Duplicate of #443. As I warned in https://github.com/bibletime/bibletime/issues/443#issuecomment-1794184100 I have now instated a permanent blocked for you from this organization due to continuous filing of the same duplicate bug, which I consider abuse.

**Closed by jaakristioja** 2024-03-03 20:12 UTC
Labels: type: BUG
