### ISSUE TITLE
Ctrl+L doesn't work

### ISSUE THREAD

**Issue by bundeskunschler** [bibletime/bibletime#102] opened 2017-05-24 10:37 UTC
Hi,

For years I've been using BibleTime, at the moment BibleTime 2.10.1 on an Ubuntu 16.04 machine (but the problem also occurred on other Ubuntu versions in the past).

The short key <kbd>Ctrl</kbd>+<kbd>L</kbd> for "change location" has never worked on my BibleTime installations - there's no effect. Additionally, when I try to change the short key (for example to <kbd>Ctrl</kbd>+<kbd>K</kbd> or <kbd>F4</kbd>, replacing the original use of <kbd>F4</kbd> starting the book shelf), it won't save the change - the next time I open the preferences window, there's <kbd>Ctrl</kbd>+<kbd>L</kbd> again.

Anyone got the same problem? Does it depend on my Linux? Anyone knows help?

**Comment by gholmlund** [comment] 2017-05-24 15:16
I just tried it on ubuntu 17.04 with BibleTime 2.10.1 and 2.11.0. It works for me. All it does is put the keyboard focus into the reference line edit box and allows you to start typing a new reference. It is very similar to how most browsers use ctrl-L.

**Comment by gholmlund** [comment] 2017-05-31 16:48
Closing as no reproducible.

**Comment by bundeskunschler** [comment] 2017-06-02 07:40
Okay, anyone got an Idea, what could be the problem on my computer? Or why I can't change the shortkeys? gholmlund, could you maybe check this as well?

**Comment by gholmlund** [comment] 2017-06-02 14:40
I can confirm that once the shortcut is changed, you can't use the shortcut in that session. It does start working if I restart BibleTime.

**Comment by gholmlund** [comment] 2017-06-03 00:09
I found two problems:
1. Ctrl-L does not work if the menu "View / Toolbars / Show toolbars in text windows" is unchecked.
2. After changing shortcuts of "All text windows", they are saved to the config file, but not used by the current BibleTime session.

Both problems have been fixed in stable-2.11 and master

**Closed** 2017-06-03 00:11 UTC
Labels: resolution: FIXED

**Comment by bundeskunschler** [comment] 2017-06-05 12:21
Thanks a lot, you've made my day! I never would have guessed it depends on the "show toolbar in text windows" checkbox ...
