### ISSUE TITLE
Bibletime and freeBSD 12.1: (gst-plugin-scanner:81033): GLib-GObject-CRITICAL

### ISSUE THREAD

**Issue by Elimelech** [bibletime/bibletime#217] opened 2020-01-06 18:54 UTC
FreeBSD 12.1, Lumina 1.5.0, Bibletime  2.11.2_2
```
$ bibletime
QKqueueFileSystemWatcherEngine::addPaths: open: No such file or directory

(gst-plugin-scanner:81033): GLib-GObject-CRITICAL **: 20:44:35.057: g_param_spec_int64: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:81033): GLib-GObject-CRITICAL **: 20:44:35.059: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:81033): GLib-GObject-CRITICAL **: 20:44:36.040: g_param_spec_int64: assertion 'default_value >= minimum && default_value <= maximum' failed

(gst-plugin-scanner:81033): GLib-GObject-CRITICAL **: 20:44:36.041: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed

(gst-plugin-scanner:81033): GLib-GObject-CRITICAL **: 20:44:37.819: validate_pspec_to_install: assertion 'G_IS_PARAM_SPEC (pspec)' failed
Trace/BPT trap

```

**Comment by jaakristioja** [comment] 2020-01-06 23:44
The information you have currently provided is insufficient for us to debug this problem.

Can you please also provide us a GDB backtrace of the crash?

Have you tried whether this also occurs with BibleTime compiled from the source code in our git master branch?

**Comment by Elimelech** [comment] 2020-01-07 00:03
How to compile your application from git master branch?

2020-01-06 23:44 GMT, Jaak Ristioja <notifications@github.com>:
> The information you have currently provided is insufficient for us to debug
> this problem.
>
> Can you please also provide us a GDB backtrace of the crash?
>
> Have you tried whether this also occurs with BibleTime compiled from the
> source code in our git master branch?
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bibletime/bibletime/issues/217#issuecomment-571364817


-- 
Желаю вам поддержки Свыше и успеха!

С уважением,
Ваш  Владимир Тимофиев <http://copi.ru/94717/>
тел./viber: +380504948657

**Comment by jaakristioja** [comment] 2020-01-18 21:58
I don't know about FreeBSD, but in general you can do something like this:

```sh
# Clone BibleTime source code from GitHub to bibletime/
git clone https://github.com/bibletime/bibletime.git

# Generate and go to build directory:
mkdir bibletime/b
cd bibletime/b

# Configure BibleTime build using custom install directory (this will probably
# fail if you are missing some build-time dependencies, like header files for
# Qt, SWORD etc):
cmake -DCMAKE_INSTALL_PREFIX=install/ ..

# Compile BibleTime:
make

# Install BibleTime to the install directory previously given to cmake:
make install

# Run BibleTime from the install directory:
install/bin/bibletime
```

**Comment by Elimelech** [comment] 2020-01-19 00:32
Everything was assembled according to your instructions:

1) #git clone https://github.com/bibletime/bibletime.git
2) #build-release.sh

Established in /usr/local/bin/bibletime
So the program works

P.S. And why, by default, your program does not work from ports
freeBSD and packages?

1)http://pkg.freebsd.org/FreeBSD:12:i386/
2) https://svnweb.freebsd.org/ports/head/misc/bibletime/


2020-01-18 21:58 GMT, Jaak Ristioja <notifications@github.com>:
> I don't know about FreeBSD, but in general you can do something like this:
>
> ```sh
> # Clone BibleTime source code from GitHub to bibletime/
> git clone https://github.com/bibletime/bibletime.git
>
> # Generate and go to build directory:
> mkdir bibletime/b
> cd bibletime/b
>
> # Configure BibleTime build using custom install directory (this will
> probably
> # fail if you are missing some build-time dependencies, like header files
> for
> # Qt, SWORD etc):
> cmake -DCMAKE_INSTALL_PREFIX=install/ ..
>
> # Compile BibleTime:
> make
>
> # Install BibleTime to the install directory previously given to cmake:
> make install
>
> # Run BibleTime from the install directory:
> install/bin/bibletime
> ```
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/bibletime/bibletime/issues/217#issuecomment-575942033


-- 
Желаю вам поддержки Свыше и успеха!

С уважением,
Ваш  Владимир Тимофиев <http://copi.ru/94717/>
тел./viber: +380504948657

**Comment by gholmlund** [comment] 2020-01-19 01:54
The gstreamer library is not directly called by BibleTime. It is loaded by Qt. 
Perhaps there is a compatibility problem between Qt and gstreamer?
Perhap the issue is only on one computer?

**Comment by jaakristioja** [comment] 2020-02-04 07:15
Looks like an upstream issue. Closing.

**Closed by jaakristioja** 2020-02-04 07:15 UTC
Labels: MORE INFORMATION NEEDED, type: BUG
