### ISSUE TITLE
Doesn't find all instances of "shepherd" in KJVA

### ISSUE THREAD

**Issue by PatrickGMM** [bibletime/bibletime#145] opened 2018-06-13 19:34 UTC
Version 2.11.1 on Linux Mint 17.2 Cinnamon:

If "shepherd" (w/o the quotes) is put into the search box in either "All words", "Some words" or "Free" modes, the instance in Psalm 23 is not found.

**Comment by gholmlund** [comment] 2018-06-16 17:51
It works for me using ESV2011 module. What module are you searching?

**Comment by PatrickGMM** [comment] 2018-06-17 01:40
I'm searching KJVA 3.0.1

**Comment by gholmlund** [comment] 2018-06-17 04:50
Can you delete the KJVA search index file and let it re-index the book. 
rm   -rf   $HOME/.bibletime/indices/KJVA

**Comment by PatrickGMM** [comment] 2018-06-17 17:49
I just tried that, and the same problem exists. Does bibletime use an external library for its search functions?

**Comment by gholmlund** [comment] 2018-06-18 02:06
We use the CLucene library for indexing and searching. Mine is:
libclucene-contribs1v5
2.3.3.4+dfsg-1
I don't think CLucene is the answer just because I don't remember it being a problem in the past.

**Comment by PatrickGMM** [comment] 2018-06-18 03:03
Thanks for the information. My version of the CLucene library is also 2.3.3.4, specifically 2.3.3.4-4build1

**Comment by gholmlund** [comment] 2018-11-01 19:23
I was able to reproduce this issue. The problem is in the sword library. I traced the issue to when the KJVA index was built. The problem was found in SWModule::stripText(). It returned a truncated text. It only happens with libsword 1.7.3 (which is still shipping in ubuntu 18.10). It does not happen with libsword 1.8.1. Since the problem is not in BibleTime and it has been fixed in libsword 1.8.1, I am closing this issue.

**Closed by gholmlund** 2018-11-01 19:23 UTC
Labels: component: Search / Indexing, component: Sword/Sword++ related, resolution: UPSTREAM ISSUE, type: BUG
