### ISSUE TITLE
Crashing in Manjaro

### ISSUE THREAD

**Issue by yeshuaphreque** [bibletime/bibletime#110] opened 2017-07-30 18:44 UTC
So I just installed Manjaro after using Ubuntu for many years.  I have used Bibletime since I first started using linux and this is the first time running into this problem.  When I open the program I can open books, some commentaries and maps but when I attempt to open any of the Bibles the program crashes and just closes out.  Any suggestions to try?

**Comment by greg-hellings** [comment] 2017-07-30 21:12
Try contacting whatever Manjaro is. As you have already pointed out, this
is peculiar to them.

**Comment by imiladsoltani** [comment] 2017-08-17 18:05
Manjaro is a linux distro based on Arch. 
And I have same issue...

**Comment by jaakristioja** [comment] 2017-08-17 18:37
Can you please provide a backtrace? For example:

```
$ gdb -q bibletime
Reading symbols from bibletime...Reading symbols from /usr/lib64/debug//usr/bin/bibletime.debug...done.
done.
(gdb) run
Starting program: /usr/bin/bibletime

Program received signal SIGSEGV, Segmentation fault.
0x00000000ac7d9784 in someclass::somefunction ()
(gdb) thread apply all bt
```

**Comment by yeshuaphreque** [comment] 2017-09-07 20:54
This is what I get after starting it from the terminal:
[dirk@StarWars ~]$ bibletime
Segmentation fault (core dumped)
[dirk@StarWars ~]$ [4060:4060:0100/000000.399298:ERROR:broker_posix.cc(41)] Invalid node channel message

**Comment by greg-hellings** [comment] 2017-09-08 05:57
Can you try running that through gdb and returning the results of a
backtrace, as Jaak previously indicated? Try the following series of
commands:

$ gdb -q bibletime

>>> r

<application will run until you cause the segmentation fault to occur>

>>> bt

After that final "bt" command, gdb will print out the backtrace that the
developers are looking for to help them assess the situation. Thanks!

**Comment by yeshuaphreque** [comment] 2017-09-09 05:32
Thread 0x7fff57b7c700 (LWP 11973) exited]
ERROR: corrupt data during decompression.

Thread 1 "bibletime" received signal SIGSEGV, Segmentation fault.
0x00007ffff0015e01 in QWidget::locale() const () from /usr/lib/libQt5Widgets.so.5
(gdb) bt full
#0  0x00007ffff0015e01 in QWidget::locale() const () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#1  0x00007ffff001ef5f in QWidgetPrivate::resolveLocale() () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#2  0x00007ffff001fa0b in QWidget::setAttribute(Qt::WidgetAttribute, bool) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#3  0x0000000000530422 in BtBibleKeyWidget::BtBibleKeyWidget(CSwordBibleModuleInfo const*, CSwordVerseKey*, QWidget*, char const*) ()
No symbol table info available.
#4  0x000000000052f2b0 in CBibleKeyChooser::CBibleKeyChooser(BtConstModuleList const&, BTHistory*, CSwordKey*, QWidget*) ()
No symbol table info available.
#5  0x000000000052b699 in CKeyChooser::createInstance(BtConstModuleList const&, BTHistory*, CSwordKey*, QWidget*) ()
No symbol table info available.
#6  0x000000000055692a in CLexiconReadWindow::initView() ()
No symbol table info available.
#7  0x0000000000546be9 in CBibleReadWindow::initView() ()
No symbol table info available.
#8  0x000000000054e088 in CDisplayWindow::init() ()
No symbol table info available.
#9  0x00000000004a335c in BibleTime::createReadDisplayWindow(QList<CSwordModuleInfo*>, QString const&) ()
No symbol table info available.
#10 0x00000000004a3941 in BibleTime::createReadDisplayWindow(CSwordModuleInfo*, QString const&) ()
No symbol table info available.
#11 0x000000000055c469 in ?? ()
No symbol table info available.
#12 0x00007fffef2f4786 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#13 0x000000000055dff2 in BtBookshelfDockWidget::moduleOpenTriggered(CSwordModuleInfo*) ()
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#14 0x00000000004c9ab3 in BtBookshelfDockWidget::slotModuleActivated(CSwordModuleInfo*) ()
No symbol table info available.
#15 0x000000000055e43c in ?? ()
No symbol table info available.
#16 0x00007fffef2f4786 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#17 0x000000000055e9d2 in BtBookshelfView::moduleActivated(CSwordModuleInfo*) ()
No symbol table info available.
#18 0x00007fffef2f4786 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#19 0x00007ffff023e306 in QAbstractItemView::activated(QModelIndex const&) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#20 0x00007ffff024149d in QAbstractItemView::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#21 0x00007ffff0289a84 in QTreeView::mouseReleaseEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#22 0x00007ffff002dd68 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#23 0x00007ffff011160f in QFrame::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#24 0x00007ffff024a4a4 in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#25 0x00007ffff02892bd in QTreeView::viewportEvent(QEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#26 0x00007fffef2c489c in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
---Type <return> to continue, or q <return> to quit---
#27 0x00007fffeffebe28 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#28 0x00007fffefff3ea1 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#29 0x00007fffef2c4bd0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#30 0x00007fffefff2e2a in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#31 0x00007ffff0048f51 in ?? () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#32 0x00007ffff004b691 in ?? () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#33 0x00007fffeffebe4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#34 0x00007fffefff3926 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
No symbol table info available.
#35 0x00007fffef2c4bd0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#36 0x00007fffef8271e4 in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) () from /usr/lib/libQt5Gui.so.5
No symbol table info available.
#37 0x00007fffef828d46 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) () from /usr/lib/libQt5Gui.so.5
No symbol table info available.
#38 0x00007fffef8004ac in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Gui.so.5
No symbol table info available.
#39 0x00007fffd7c5bcc1 in ?? () from /usr/lib/libQt5XcbQpa.so.5
No symbol table info available.
#40 0x00007fffebfe3a57 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
---Type <return> to continue, or q <return> to quit---
No symbol table info available.
#41 0x00007fffebfe3c88 in ?? () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#42 0x00007fffebfe3d1c in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
No symbol table info available.
#43 0x00007fffef31f061 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#44 0x00007fffef2c2ffb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#45 0x00007fffef2cc048 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
No symbol table info available.
#46 0x000000000049f245 in main ()
No symbol table info available.

**Comment by gholmlund** [comment] 2017-09-09 21:03
This is a duplicate of BT bug #114.

This is caused by a Qt 5.9 bug (QTBUG-61213) . The Qt bug has not yet been fixed, however a work around was checked into the stable.2.11 branch and master branch. This fix will be released when stable-2.11.1 occurs.

commit 0538dd7
Author: Gary Holmlund gary.holmlund@gmail.com
Date: Fri Jun 2 21:04:56 2017 -0700
Fix crash with Qt 5.9. This is a workaround for QTBUG-61213

**Closed by gholmlund** 2017-09-09 21:03 UTC
Labels: component: Qt related, resolution: DUPLICATE, resolution: FIXED, resolution: UPSTREAM ISSUE

**Comment by mgruner** [comment] 2017-09-11 09:40
@gholmlund @jaakristioja can we have another release for 2.11? What about giving maintenance release rights to Gary?

**Comment by greg-hellings** [comment] 2017-09-11 11:30
For one of my projects at work we have releases made by Travis CI automatically whenever a new tag is pushed to the repository. It might be worthwhile to update our .travis.yml file to handle cutting a release by a similar mechanism.

**Comment by jaakristioja** [comment] 2017-09-16 11:50
@mgruner afaik there are no technical hindrances to it, neither am I clinging to my team position at this point. Please lets move this discussion to another issue, to stop spamming the original poster and anyone else registered to receive notifications from this issue. Thanks.
