### ISSUE TITLE
[BUG] Cannot install OSHB module

### ISSUE THREAD

**Issue by entodoays** [bibletime/bibletime#352] opened 2021-11-05 07:34 UTC
**Bug description**
On my Bibletime 3.0.2 snap version on Ubuntu 21.10 I tried installing OSHB Hebrew module from the Crosswire repo and got an error, "Some modules were not installed".

**Steps to reproduce**
1. Go to Bookshelf manager
2. Click on install
3. Try to install the Hebrew (ancient) module named OSHB from the Crosswire repo.

**System information:**
 - Ubuntu 21.10
 - BibleTime Version 3.02
 - BibleTime was installed from Snapstore

**Comment by entodoays** [comment] 2021-11-05 17:31
I managed to install the module manually by downloading the zip file from the crosswire.org site and unzipping it in the .sword folder.

**Comment by gholmlund** [comment] 2021-11-06 01:51
I tried it and it worked correctly for me.

**Comment by jaakristioja** [comment] 2021-11-14 12:37
@entodoays Could you please try running BibleTime with the `--debug` command-line option to enable logging of debug messages to the console, try to reproduce the issue and post the log messages BibleTime outputs to the console? Thanks!

I think we should at minimum make the error message in the UI a bit more verbose.

**Comment by jaakristioja** [comment] 2021-11-14 13:03
> @entodoays Could you please try running BibleTime with the `--debug` command-line option to enable logging of debug messages to the console, try to reproduce the issue and post the log messages BibleTime outputs to the console? Thanks!

Actually, after taking a look at the code responsible for the installation, I don't think the `--debug` output is necessary. It will probably not output anything of interest, and the related warning message `Error with install: -1 module: OSHB`. This is due to the underlying Sword library not reporting detailed errors. I think there is nothing we can currently do to improve the the error reporting or fix anything in code without rewriting (parts of the) Sword library, and we don't currently have the resources to rewrite it.

However, it seems that the actual failure you're experiencing might not be directly related to bugs in the Sword code either. I suspect this might be an issue with snap packaging. I'll try to reproduce this with a fresh install of Ubuntu 21.10 and BibleTime from snap.

**Comment by jaakristioja** [comment] 2021-11-14 14:21
I am able to reproduce this issue. Although I'm also seeing a lot of errors related to Snap, e.g. `ENOENT` when not being able to open files from under `/home/user/snap/bibletime/13/.sword/InstallMgr/20081216195754/modules/`, the issue at hand seems to be related to the Curl FTP transport used by libsword, which apparently times out during transfer without an apparent reason:

```
CURLFTPTransport report progress: totalSize: 3036366; xfered: 0

CURLFTPTransport: <= Recv header: 150 Opening BINARY mode data connection for ot.bzz (3036366 bytes).

CURLFTPTransport: TEXT: Maxdownload = -1

CURLFTPTransport: TEXT: Getting file with size: 3036366

CURLFTPTransport report progress: totalSize: 3036366; xfered: 0

/.../

CURLFTPTransport report progress: totalSize: 3036366; xfered: 2454360

CURLFTPTransport: TEXT: Operation timed out after 10000 milliseconds with 2454360 out of 3036366 bytes received

CURLFTPTransport report progress: totalSize: 3036366; xfered: 2454360

CURLFTPTransport: TEXT: Closing connection 0

***** Finished performing curl easy action. 

copyDirectory: failed to get file ftp://ftp.crosswire.org/pub/sword/raw/modules/texts/ztext/oshb/ot.bzz

(BibleTime 3.0.2) WARNING: Error with install:  -9 module: "OSHB"
```

It timed out while still actually downloading, there was not a 10000 millisecond wait between the last report progress messages and the timeout.

**Comment by jaakristioja** [comment] 2021-11-14 14:50
It appears that libsword uses [`CURLOPT_TIMEOUT`](https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html) and [`CURLOPT_TIMEOUT_MS`](https://curl.se/libcurl/c/CURLOPT_TIMEOUT_MS.html) options to libcurl to specify a timeout for how long transfers are allowed to take, with the default being at 10000 milliseconds (10 seconds). The respective libcurl documentation states

> Since this puts a hard limit for how long time a request is allowed to take, it has limited use in dynamic use cases with varying transfer times.

and also suggests that

> You are then advised to explore CURLOPT_LOW_SPEED_LIMIT, CURLOPT_LOW_SPEED_TIME or using CURLOPT_PROGRESSFUNCTION to implement your own timeout logic.

Unfortunately, this is not what libsword currently does. I don't remember having encountered this bug before before, so my first suspicion is that the libcurl semantics might have changed, however the libcurl webpage [states](https://curl.se/libcurl/features.html#stableapi) that they have not broken compatibility since 2006. Dunno, perhaps it just didn't work before, and they have fixed it? Either way, it seems that the current libsword behavior is broken.

**Comment by jaakristioja** [comment] 2021-11-14 15:12
I've filed an upstream bug report about the libsword behavior to https://tracker.crosswire.org/browse/API-251 and will shortly push some commits to work around this issue.

**Comment by jaakristioja** [comment] 2021-11-14 15:25
Pushed 3f9cd4a1d64c468e36e2854b7bce4966d09907eb to master and 64f28af78ce49513a49cd500a0dce8e655dd476e to stable-3.0 to work around this.

**Comment by jaakristioja** [comment] 2021-11-14 15:44
Also filed #354 to improve the related error messages presented in the UI.

The workaround will be part of BibleTime 3.0.3.

Marking this bug as fixed, but not yet closing.

@entodoays Could you please confirm that you're also getting a `CURLFTPTransport: TEXT: Operation timed out after 10000 milliseconds` message when running `bibletime --debug` from the command line and attempting to install the OSHB module?

**Comment by jaakristioja** [comment] 2021-11-14 20:56
> I don't remember having encountered this bug before before, so my first suspicion is that the libcurl semantics might have changed, however the libcurl webpage [states](https://curl.se/libcurl/features.html#stableapi) that they have not broken compatibility since 2006.

The reason why we might not have seen this occur before (or often) appears to be that libsword changed its behavior in SVN 3782 (August 27, 2020), which included `CURLOPT_TIMEOUT` changing from 45 seconds to 10 seconds. See https://github.com/bibletime/crosswire-sword-mirror/commit/bdd9bab53fdc15864e550d3a7d9eb0cf8ab82060.

**Comment by jaakristioja** [comment] 2021-11-14 23:28
Also pushed 7c4617bb92b92e88ba433d34aea626444ea29d52 to master and 8fffa8456c628f1f5da18455600bcc94cbb91a71 to stable-3.0 to support older versions of libsword.

**Comment by jaakristioja** [comment] 2022-02-06 11:54
@entodoays Could you please confirm that you're also getting a `CURLFTPTransport: TEXT: Operation timed out after 10000 milliseconds` message when running `bibletime --debug` from the command line and attempting to install the OSHB module?

**Comment by entodoays** [comment] 2022-02-07 10:00
I tried uninstalling the OSHB module and install it from the repos and I got the following error messages:
```
CURLFTPTransport: TEXT: Operation timed out after 10000 milliseconds with 2681280 out of 3036366 bytes received

CURLFTPTransport report progress: totalSize: 3036366; xfered: 2681280

CURLFTPTransport: TEXT: Closing connection 0

***** Finished performing curl easy action. 

copyDirectory: failed to get file ftp://ftp.crosswire.org/pub/sword/raw/modules/texts/ztext/oshb/ot.bzz

(BibleTime 3.0.2) WARNING: Error with install:  -9 module: "OSHB"
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Checking working directory for mods.conf...
Checking working directory for mods.d...
found.
LOADING MODULE LIBRARY...
libsword: SWMgr::createAllModules
libsword: SWMgr::createAllModules
LOADING MODULE LIBRARY COMPLETE.
LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

LocaleMgr::getLocale failed to find en_US

```
The last message repeats over and over for many pages.

**Comment by jaakristioja** [comment] 2022-02-11 18:42
Thanks! 😃 

I think the `LocaleMgr::getLocale failed to find en_US` message is usually harmless.

Closing, because the log output seems to confirm that the original issue was indeed caused by the timeout, and workarounds for this were added to the repository, Please reopen, if this issue still occurs if BibleTime is compiled with the commits mentioned in [my comment above](https://github.com/bibletime/bibletime/issues/352#issuecomment-968385575), e.g. with the a future release of BibleTime.

**Closed by jaakristioja** 2022-02-11 18:42 UTC
Labels: type: BUG, component: Sword/Sword++ related, resolution: FIXED, component: Backend
