### ISSUE TITLE
My Bookshelf Is Having Trouble Finding/Using the Downloaded Modules

### ISSUE THREAD

**Issue by worthywoman** [bibletime/bibletime#101] opened 2017-05-13 20:13 UTC
I hope they give you the information you need to help me figure out what to do. Coding is not in my skill set.

If I knew where the "troubleshooting" for BibleTime was, I would have started there. Maybe if I become more knowledgeable, I could help with that.

Every time I run BibleTime opens, the Bookshelf opens, telling me to download books. I think I found them on the hard drive at D:\Program Files (x86)\BibleTime\Sword 

(I looked because the Bookshelf Manager said that it was the Install Folder.)

My system is Windows 10 Pro 64 bit warning on an Acer Veriton. I don't remember which number off hand, I'm sorry. The other thing that you may need to know that my mouse is Dragon NaturallySpeaking.

**Comment by gholmlund** [comment] 2017-05-14 04:33
I believe that this is the same issue as bug #90, which has been fixed, but not yet released. The basic problem is that the program is trying to create a "Sword" and "BibleTime" directory to store modules and settings. It is creating them in the wrong directory and does not have permissions to properly create them.

I am going to try to get a patched version of BibleTime for Windows to you in 1 or 2 days. If this fixes the problem we know it is the same a bug #90.

**Comment by gholmlund** [comment] 2017-05-15 22:46
I have the patched version of BibleTime ready. Please download this and then see if your problem is fixed. If you were able to install any documents you will probably have to do that again.
http://sourcearchives.com/downloads/BibleTime-2.11.x-win32.exe

**Comment by worthywoman** [comment] 2017-05-16 01:30
I was so not expecting a fast response like this!

Tomorrow is a possibility for me doing this. Most likely, it will be Friday. I'm just spreading myself too thin!

Thank you so much!

**Comment by worthywoman** [comment] 2017-05-20 20:04
![2017-05-20](https://cloud.githubusercontent.com/assets/12615221/26278978/70328c10-3d6d-11e7-81cc-c236a3969300.png)

I think you fixed it! Look at all my new toys!

Thank you!

**Comment by gholmlund** [comment] 2017-05-22 01:45
Closing as a duplicate of #90

**Closed by gholmlund** 2017-05-22 01:45 UTC
Labels: resolution: DUPLICATE
