### ISSUE TITLE
Finnish language BT Bible book names are english

### ISSUE THREAD

**Issue by ilkant** [bibletime/bibletime#236] opened 2020-05-15 16:24 UTC
BT 3.0.0 RC1 installed with snap to Kubuntu 18.04. BT menus are finnish language. Finnish bibles have english names like Proverbs 1:6, should be Sananlaskut 1:6. This occurs to every 5 finnish bibles. And at least russian language RusVZh have english names.

**Comment by ilkant** [comment] 2020-05-15 16:37
In BibleTime Settings there are only english or american english available to choose.

**Comment by jaakristioja** [comment] 2020-05-17 19:42
I think that the Sword library is unable to find its locales, i.e. `sword::LocaleMgr::getSystemLocaleMgr()->getAvailableLocales()` does not return much. So i guess this is either a bug in Sword or caused by our packaging of it in the snap. I find the latter more likely as the immediate cause of this bug. Perhaps the locales are not there or Sword is unable to find them. It might also be that Sword does not like being contained in a snap.

**Comment by jaakristioja** [comment] 2020-05-17 19:49
@gholmlund Can this be solved by something like
```ini
[Install]
LocalePath=something
```
in a `~/sword/sword.conf` or `/etc/sword.conf` equivalent in the snap?

**Comment by ilkant** [comment] 2020-05-17 20:01
I have on my Kubuntu 18.4 directory ~/.sword/ where are InstallMgr mods.d
modules.

In mods.d directory
$ less ~/.sword/mods.d/finbiblia.conf

[FinBiblia]
DataPath=./modules/texts/ztext/finbiblia/
ModDrv=zText
Lang=fi
Version=1.1
History_1.1=Compressed module (2003-02-20)
BlockType=BOOK
CompressType=ZIP
SourceType=GBF
Description=Finnish Biblia (1776)
SwordVersionDate=2003-02-20
MinimumVersion=1.5.2
About=Biblia, Se on: Koko Pyh<E4> Raamattu, Suomeksi.\par Vuoden 1776
kirkkoraamattu.\par\par Finnish Bible published in 1776.\par\par In public
domain.\par\par SWORD version by Tero Favorin (tero at favorin dot com)
LCSH=Bible. Finnish.
DistributionLicense=Public Domain
InstallSize=1726792


And /etc/sword.conf contains two lines:

[Install]
DataPath=/usr/share/sword/

And $ ls /usr/share/sword/locales.d
abbr.conf          bg-utf8.conf    de_abbrev-utf8.conf  et-utf8.conf
        fr-utf8.conf  it.conf              la.conf       nl.conf
       pt_BR-utf8.conf    ru-utf8.conf  uk_UA-cp1251.conf
    zh_TW-utf8.conf
af.conf            cs.conf         de.conf              fa-utf8.conf
        ga-utf8.conf  it-utf8.conf         la-utf8.conf  nl-utf8.conf
  pt.conf            sk.conf       uk_UA-koi8-u.conf
af-utf8.conf       cs-utf8.conf    de-utf8.conf         fi.conf
             he-utf8.conf  iu-utf8.conf         locales.conf  no.conf
       pt-utf8.conf       sk-utf8.conf  uk-utf8.conf
ar_EG-cp1256.conf  cy.conf         es.conf              fi-utf8.conf
        hr-utf8.conf  ja-utf8.conf         lt-utf8.conf  no-utf8.conf
  ro.conf            sl.conf       vi-utf8.conf
ar_EG-utf8.conf    cy-utf8.conf    es-utf8.conf         fo-utf8.conf
        hu.conf       ko_abbrev.conf       Makefile.am   pl.conf
       ro-utf8.conf       sl-utf8.conf  zh_CN-utf8.conf
ar-utf8.conf       da.conf         et_abbr.conf         fr_abbrev.conf
      hu-utf8.conf  ko_abbrev-utf8.conf  mt-utf8.conf  pl-utf8.conf
  ru_RU-cp1251.conf  sv.conf       zh_english-utf8.conf
az-utf8.conf       da-utf8.conf    et_abbr-utf8.conf    fr_abbrev-utf8.conf
 id.conf       ko.conf              nb.conf       pon_utf8.conf
 ru_RU-koi8-r.conf  sv-utf8.conf  zh_Hans-utf8.conf

bg_BG-cp1251.conf  de_abbrev.conf  et.conf              fr.conf
             id-utf8.conf  ko-utf8.conf         nb-utf8.conf  pt_BR.conf
    ru_RU-utf8.conf    th-utf8.conf  zh_Hant-utf8.conf

i


su 17. toukok. 2020 klo 22.49 Jaak Ristioja (notifications@github.com)
kirjoitti:

**Comment by gholmlund** [comment] 2020-05-18 04:37
I found that sword was not finding the locales.d directory. It was not on any of the standard paths. One method of fixing it is to change directory to the sword directory before launching BibleTime. I did this inside of the snap by using a wrapper shell script. It seems to work fine. 

I will do a little more testing tomorrow and then release a new snap.

**Comment by LAfricain** [comment] 2020-05-18 14:01
The same problem in the magnifer in French:
![magnifer_ref](https://user-images.githubusercontent.com/19690477/82221531-6aead700-9920-11ea-959a-a13f061e1574.png)

And I have too encoding  issues with in the book names field:
![encoding_issue](https://user-images.githubusercontent.com/19690477/82221871-d6cd3f80-9920-11ea-94b8-63db4041cd81.png)

**Comment by gholmlund** [comment] 2020-05-18 14:36
This defect is about missing book names in non-english.
See my comment above. I have updated the snap to include this fix. Please test.

**Comment by LAfricain** [comment] 2020-05-18 14:51
I compiled it on my system why I don't have the fix?

**Comment by gholmlund** [comment] 2020-05-18 14:59
@LAfricain  What you are reporting is a different issue from this bug. This is was that there is only one language choice (english) in the config dialog for Bible book name. 

Please file a different bug report and provide some details about what was installed onto what os, etc.

**Comment by LAfricain** [comment] 2020-05-18 16:20
OK.

**Comment by gholmlund** [comment] 2020-05-24 23:34
The original issue of this bug has been fixed. It was unique to the snap packaging. Closing.

**Closed by gholmlund** 2020-05-24 23:34 UTC
Labels: component: Packaging/Releases, component: Sword/Sword++ related, type: BUG

**Comment by jaakristioja** [comment] 2020-06-05 21:07
@gholmlund Fixed where exactly?

**Comment by gholmlund** [comment] 2020-06-05 23:03
Fixed in repository:  bibletime / build-snap 
May 27, 2020
efac3aa4503e830454e39d5ffd13e8a6d2eed707

**Comment by jaakristioja** [comment] 2020-06-06 14:25
Ok, thnx. I somehow missed that commit.
