### ISSUE TITLE
[BUG] 5 columns yields shrink of rows.

### ISSUE THREAD

**Issue by Gwang-Jin** [bibletime/bibletime#324] opened 2021-05-31 01:51 UTC
**Describe the bug**
When I added 5 columns of bible text or commentaries, I saw a shrink of rows. BibleTime works well up to 4 columns. But over 5 columns yielded some problem. Thank you.

**To Reproduce**
1. Add 5 columns (text or commentary)
2. Preferences > Font size 18.

**Expected behavior**

**Screenshots**
If applicable, please add screenshots to help explain your problem.

<img width="1278" alt="screen01" src="https://user-images.githubusercontent.com/36105353/120128627-6fb5bc80-c1fd-11eb-8aba-6a2e2efc01fa.png">

<img width="609" alt="screen02" src="https://user-images.githubusercontent.com/36105353/120128631-72b0ad00-c1fd-11eb-9086-6486008da837.png">

**System information (please complete the following information):**
 - OS and OS version: MacOS
 - BibleTime Version : 3.0.0
 - How BibleTime was installed : dmg
 - Versions of modules related to the crash (if known)

**Additional context**
Add any other context about the problem here, e.g. including output of `bibletime --debug` and/or backtraces in case of crashes.

**Comment by gholmlund** [comment] 2021-06-01 05:07
This is a duplicate of bug #268 and is already fixed for the next release.

**Closed by gholmlund** 2021-06-01 05:07 UTC
Labels: resolution: DUPLICATE, type: BUG
