### ISSUE TITLE
[Feature Request] In-App Localization / UI Language Selection

### ISSUE THREAD

**Issue by historical-theology** [bibletime/bibletime#192] opened 2019-08-30 15:04 UTC
It would be a boon to people studying the Bible worldwide to have the option to select the localization / UI language inside the BibleTime application rather than relying on the system's localization settings.

Since the localization settings are already stored locally for BibleTime's use (e.g. "/usr/share/bibletime/locale/" in Linux), I would not imagine this to be a difficult feature to implement.

Here is where I imagine this option fitting:
Settings --> Configure BibleTime --> Localization (UI)
(perhaps directly above or directly under the "Language for names of biblical books" option)

If you would be willing to add this as an option, then BibleTime would be worth translating into any language that lacks proper operating system-wide support.

For one example, if the feature should be added, then I would be happy to start a Latin translation project for BibleTime on transifex.

Thank you for your consideration.

God bless.

**Comment by ngaretou** [comment] 2020-07-03 11:21
I second this one! Users aren't always able to get the OS that matches their preferred computing language - used computers in the country we live in often come from the US in English and then can't be changed (unless running Windows Pro), so in-app localization choice is a necessity for our target audience. Thanks for considering this!

**Comment by jaakristioja** [comment] 2020-07-11 10:24
I agree. However, since this is actually a duplicate of #1, which was once marked WONTFIX, it makes sense to reopen the original issue instead.

**Closed by jaakristioja** 2020-07-11 10:24 UTC
Labels: component: Frontend, component: Translations, resolution: DUPLICATE, type: ENHANCEMENT
