### ISSUE TITLE
BibleTime Core Dumped

### ISSUE THREAD

**Issue by aaronTHJ** [bibletime/bibletime#55] opened 2016-03-12 00:18 UTC
I found another bug when running `./build-debug.sh`:

`Linking CXX executable bibletime
Updating UI translation for bibletime_ui_es.qm
make[2]: /usr/lib/i386-linux-gnu/qt5/bin/lrelease: Command not found
make[2]: *** [bibletime] Error 127
make[1]: *** [CMakeFiles/bibletime.dir/all] Error 2
make: *** [all] Error 2
`

I wanted to see if it was a big error so I tried `./bibletime` and I get:

`(BibleTime 2.10.0_rc1+5f9b8c7b5ad4de6c6701e7cafec31768e4d31e8b) WARNING: Cannot find icon directory relative to "~/bibletime" 
(BibleTime 2.10.0_rc1+5f9b8c7b5ad4de6c6701e7cafec31768e4d31e8b) FATAL: Error initializing directory cache!
Please report this bug at https://github.com/bibletime/bibletime/issues
Aborted (core dumped)
`

**Comment by gholmlund** [comment] 2016-03-12 01:40
lrelease is a Qt translation tool. You need to install it before building. Also, the bibletime executable will be installed in a location that is not the same place the build initially puts it. Make sure you "make install" and run the bibletime that is installed. This is not a bug.

**Closed by gholmlund** 2016-03-12 01:40 UTC
