### ISSUE TITLE
[QUESTION] deb-Package for easy installation

### ISSUE THREAD

**Issue by FabulousOne** [bibletime/bibletime#379] opened 2022-04-20 19:03 UTC
**Background**
I tried to install bibletime, but found out that this tar.xz file is to be built. Now, I am not familiar with it.

**Question**
Would it be possible to host here a .deb-package, so that no so tech-savvy users can install bibletime? In my distro repositories, there is only bibletime 2 available (Linux Mint 20.3), and I would like to upgrade to the new version.

Thank you!

**Comment by jaakristioja** [comment] 2022-04-24 21:25
Duplicate of #258. That's the plan, but we have not yet gotten that far.

**Closed by jaakristioja** 2022-04-24 21:25 UTC
Labels: type: QUESTION
