### ISSUE TITLE
Bibletime fails to start with fatal error

### ISSUE THREAD

**Issue by cscj001** [bibletime/bibletime#443] opened 2023-11-05 18:30 UTC
**Bug description**
When starting bibletime, I get the following error:  $ bibletime
(BibleTime 3.0.2) FATAL: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile)

**Steps to reproduce**
1. enter bibletime in terminal
2. see error

**Expected behavior**
Bibletime in same state as when last exited program/

**System information:**
 - Ubuntu 22.04.3
 - BibleTime 3.0.2-1
 - Installed from system packages
 - Versions of modules related to the crash Unknown

**Additional context**
bibletime --debug
LOOKING UP LOCALE DIRECTORY...
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Checking working directory for mods.conf...
Checking working directory for mods.d...
Checking working directory ../library/ for mods.d...
Checking $SWORD_PATH...
Parsing /etc/sword.conf...
Checking for /etc/sword.conf...
found.
DataPath in /etc/sword.conf is set to /usr/share/sword/.
Checking for mods.conf in DataPath...
Checking for mods.d in DataPath...
found.
LOOKING UP LOCALE DIRECTORY COMPLETE.
LocaleMgr::loadConfigDir loading /usr/share/sword/locales.d
LOOKING UP MODULE CONFIGURATION...
Checking for provided SWConfig("sword.conf")...
Checking working directory for sword.conf...
Checking working directory for mods.conf...
Checking working directory for mods.d...
Checking working directory ../library/ for mods.d...
Checking $SWORD_PATH...
Parsing /etc/sword.conf...
Checking for /etc/sword.conf...
found.
DataPath in /etc/sword.conf is set to /usr/share/sword/.
Checking for mods.conf in DataPath...
Checking for mods.d in DataPath...
found.
LOOKING UP MODULE CONFIGURATION COMPLETE.
LOADING MODULE CONFIGURATIONS...
LOADING MODULE CONFIGURATIONS COMPLETE.
LOADING MODULE LIBRARY...
libsword: SWMgr::createAllModules
libsword: SWMgr::createAllModules
LOADING MODULE LIBRARY COMPLETE.
(BibleTime 3.0.2) FATAL: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples -1, swapBehavior QSurfaceFormat::DoubleBuffer, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Please report this bug at https://github.com/bibletime/bibletime/issues
Aborted (core dumped)

**Comment by jaakristioja** [comment] 2023-11-06 06:51
You've already filed this duplicate of #125, #170, #176, #295, #419, #429 and #434 for the 5th time by yourself now. Please stop. I'm blocking you for 30 days to prevent you from filing this bug again. If you file another duplicate of this issue, I will instate a permanent block.

**Closed by jaakristioja** 2023-11-06 06:51 UTC
Labels: type: BUG

**Comment by jaakristioja** [comment] 2023-11-06 07:57
The cause is outdated graphics drivers or graphics drivers not supporting hardware acceleration. The workaround is to try to force Qt use software rendering only, e.g. by using an environment variable like `QT_OPENGL=software`.
