### ISSUE TITLE
[Feature Request] Allow selecting text for copying

### ISSUE THREAD

**Issue by PapistPenguin** [bibletime/bibletime#189] opened 2019-08-09 19:14 UTC
Hello. I find it difficult to copy text using BibleTime. I cannot just click and drag. The copy box is also difficult to use, especially since it never selects the reference my cursor is over but one that is at the bottom of the window (and scrolling can be difficult enough as it is). I would love to just be able to click and select and copy.

BibleTime 2.11.0_rc1
Ubuntu 19.04 x64

**Comment by gholmlund** [comment] 2019-08-20 00:59
The same changes that allow for continuous scrolling also bring some limitations with copying. Each verse is a separate Qt item. I may not be also to allow selecting of multiple verses by dragging. In the current implementation, dragging is used to create a bookmark, not selecting. 
This is what I believe I could do to improve this area. 
1. Make bookmark creation a context menu instead of a drag. 
2. This allows selection within a verse, so a select / copy menu could be made to work.
3. Improve the copy dialog so the verse it opens with is the one under your cursor. 
Any discussion before I start doing this?

**Comment by gholmlund** [comment] 2019-10-05 14:57
I have changed BibleTime to allow selecting verses and the copy dialog will use this selection. It even works quite well when parallel texts are used. 

The snap is available here:
http://sourcearchives.com/downloads/bibletime_master-HEAD_amd64.snap

Install it like this:
sudo snap install --dangerous bibletime_master-HEAD_amd64.snap

Notes about the snap:
120 MBytes
Ignore the BibleTime version number.
The first time the snap starts may take 1 or 2 minutes. It is fast after that.
The snap runs in its own file space so it will not find your $HOME/.bibletime or $HOME/.sword

**Comment by LAfricain** [comment] 2019-10-07 02:00
I experience some difficulties about copy/paste. I would like sometimes just copy a part of the verse, but it's not possible. Or I wouldn't have always the ref in the copied text, only the text.

**Comment by gholmlund** [comment] 2019-10-07 21:11
Because of the method used to do the continuous scrolling, partial selection of a verse is not possible. I have though for a long time about this issue, but technical problems prevent a solution to this.

**Comment by LAfricain** [comment] 2019-10-07 22:20
> partial selection of a verse is not possible

Ok, but almost doing the copy without copying automatically the Ref is it possible? I use the copy/paste to put the refs in works with LO word processor.

**Comment by LAfricain** [comment] 2019-10-07 23:59
The problem is bigger  than I thought. By instance in the fredaw module, it's now impossible to copy only a part of an article...

**Comment by LAfricain** [comment] 2019-11-01 14:04
I found an interesting solution. Just put the cursor on the verse number, than copy what you need in the mag windows.

**Comment by gholmlund** [comment] 2019-11-05 05:01
I believe this is fixed now. I updated the snap for your testing. See install instructions above.

**Comment by LAfricain** [comment] 2019-11-05 13:58
Yes it works perfectly! Thanks, but I lost all the ref link (no more working)...

**Comment by gholmlund** [comment] 2019-11-05 15:18
I am not sure what you mean by "ref link". I have checked the verse cross references and they are working.

**Comment by LAfricain** [comment] 2019-11-05 15:57
Yes the crossreferences. Is it working with the french calendrier liturgique catholique 2019? Or itnomiBibbia?

**Comment by gholmlund** [comment] 2019-11-05 16:57
I see that they don't work on these 2 modules. They also don't work with BT 2.11.2. Please open a separate request about this.

**Comment by LAfricain** [comment] 2019-11-05 17:34
But it works on my current installation.

**Comment by gholmlund** [comment] 2019-12-11 17:46
This should have been closed earlier. Closing.

**Closed by gholmlund** 2019-12-11 17:46 UTC
Labels: component: frontend, type: ENHANCEMENT

**Comment by LAfricain** [comment] 2019-12-11 19:48
If you have a snap for test, please paste the link here.

**Comment by gholmlund** [comment] 2019-12-11 19:58
See Oct 5th entry.
