### ISSUE TITLE
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed

### ISSUE THREAD

**Issue by TrophyNinjaShrub** [bibletime/bibletime#295] opened 2021-02-04 21:46 UTC
Crash at startup

~ $ bibletime 

(bibletime:91581): Gtk-WARNING **: 16:44:44.189: Theme parsing error: gtk.css:6342:10: 'height' is not a valid property name
(BibleTime 2.11.2) WARNING: QGLXContext: Failed to create dummy context
(BibleTime 2.11.2) WARNING: WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
(BibleTime 2.11.2) FATAL: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Please report this bug at https://github.com/bibletime/bibletime/issues
Aborted (core dumped)

Exit code was 134

**Comment by TrophyNinjaShrub** [comment] 2021-02-04 21:52
````
~ $ lsb_release -a ; uname -a
No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 20.10
Release:	20.10
Codename:	groovy
Linux pop-os 5.8.0-7630-generic #32~1609193707~20.10~781bb80-Ubuntu SMP Tue Jan 5 21:29:56 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
````

To be clear, it was running recently but I've done an apt upgrade since then.

I see this recommendation `QT_OPENGL=software` over here: https://github.com/bibletime/bibletime/issues/176

That does change the messages up to the crash:

````
~ $ export QT_OPENGL=software
~ $ bibletime 

(bibletime:92080): Gtk-WARNING **: 16:47:40.085: Theme parsing error: gtk.css:6342:10: 'height' is not a valid property name
(BibleTime 2.11.2) WARNING: QGLXContext: Failed to create dummy context
(BibleTime 2.11.2) WARNING: WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
(BibleTime 2.11.2) FATAL: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Please report this bug at https://github.com/bibletime/bibletime/issues
Aborted (core dumped)
   ###   134 = Unknown error 134   ###  
````

I do see other similar tickets closed with something along the lines of can't reproduce. 
https://github.com/bibletime/bibletime/issues/125

But I have other Qt-based applications running. Let me know if there's further experimentation you'd like me to try.

**Comment by TrophyNinjaShrub** [comment] 2021-02-04 21:53
For what it's worth the splash screen does show visible.

In gdb:

````
(BibleTime 2.11.2) FATAL: Failed to create OpenGL context for format QSurfaceFormat(version 2.0, options QFlags<QSurfaceFormat::FormatOption>(), depthBufferSize 24, redBufferSize -1, greenBufferSize -1, blueBufferSize -1, alphaBufferSize -1, stencilBufferSize 8, samples 0, swapBehavior QSurfaceFormat::DefaultSwapBehavior, swapInterval 1, colorSpace QSurfaceFormat::DefaultColorSpace, profile  QSurfaceFormat::NoProfile) 
Please report this bug at https://github.com/bibletime/bibletime/issues

Thread 1 "bibletime" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x00007ffff6325864 in __GI_abort () at abort.c:79
#2  0x0000555555611d05 in  ()
#3  0x00007ffff68f7488 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007ffff68f75a9 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007ffff68c4b8a in QMessageLogger::fatal(char const*, ...) const () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007fffee5d841b in  () at /lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5
#7  0x00007fffee5d8742 in  () at /lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5
#8  0x00007fffee5dade5 in QQuickWidget::resizeEvent(QResizeEvent*) () at /lib/x86_64-linux-gnu/libQt5QuickWidgets.so.5
#9  0x00007ffff7bd7d9d in  () at /lib/x86_64-linux-gnu/libQt5WebEngineWidgets.so.5
#10 0x00007ffff75d8d64 in QWidget::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff7597013 in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff6ae11ca in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff75d055e in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) ()
    at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff75d4cb7 in QWidgetPrivate::show_helper() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff75d4c59 in QWidgetPrivate::showChildren(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff75d4cd3 in QWidgetPrivate::show_helper() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff75d7e73 in QWidgetPrivate::setVisible(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff75d4c41 in QWidgetPrivate::showChildren(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff75d4cd3 in QWidgetPrivate::show_helper() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff75d4c59 in QWidgetPrivate::showChildren(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff75d4cd3 in QWidgetPrivate::show_helper() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#22 0x00007ffff75d7e73 in QWidgetPrivate::setVisible(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff75d4c41 in QWidgetPrivate::showChildren(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff75d4cd3 in QWidgetPrivate::show_helper() () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#25 0x00007ffff75d7e73 in QWidgetPrivate::setVisible(bool) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#26 0x000055555562896f in main ()
````

**Comment by jaakristioja** [comment] 2021-02-04 22:20
This appears to be a duplicate of #170. Closing.

**Closed by jaakristioja** 2021-02-04 22:20 UTC
