### ISSUE TITLE
[BUG] Handbook won't open in ver 3.0.2 on Mint 19.2 Tina

### ISSUE THREAD

**Issue by MrFishigan** [bibletime/bibletime#341] opened 2021-09-10 12:36 UTC
**Bug description**
Handbook on Help Tab will not function

**Steps to reproduce**
1. Go to Help Tab
2. Click on Handbook
3. Nothing Happens

**Expected behavior**
The Handbook should open...

**System information:**
 - OS and OS version: Mint 19.2 Tina
 - BibleTime Version 3.0.2
 - How BibleTime was installed: Package Installer via Software Manager

**Comment by jaakristioja** [comment] 2021-09-14 20:58
This is most likely caused by the Mint package(s) installing the relevant documentation in unexpected locations and BibleTime is not able to find the relevant files at runtime.

As BibleTime developers don't currently directly package BibleTime for Mint nor have the capacity to timely debug all issues specific to certain distributions, I suggest contacting the authors of the specific package (or Mint) to fix this issue.

Therefore I'm currently closing this issue report, but feel free to reopen this if necessary. If you file a downstream bug report about this, please also paste a link here for reference.

----
PS: We are aware that the BibleTime build system logic choosing the install location for the documentation is not perfect, and would be grateful to receive constructive advice, guidance or pull requests from distributions and packagers about how to improve it.

**Closed by jaakristioja** 2021-09-14 20:58 UTC
Labels: type: BUG
