### ISSUE TITLE
Russian localization only works when I started BibleTime from console

### ISSUE THREAD

**Issue by DrMoriarty** [bibletime/bibletime#148] opened 2018-06-20 07:21 UTC
Hello again!
I'm using the last release for macosx (2.11.2) Also I saw this issue on all 2.11.x versions.
When I start the application as regular user (double click from Applications folder, or from Launchpad) it starts with english localization.
When I start the app from the terminal it works in russian as expected.

This one I started as normal user:
![2018-06-20 10 09 28](https://user-images.githubusercontent.com/1177068/41642820-1bbddaf8-7472-11e8-9daf-a2b433a3e28f.png)

This one I started as `bash-3.2$ open /Applications/BibleTime.app`
![2018-06-20 10 08 26](https://user-images.githubusercontent.com/1177068/41642875-4a85012c-7472-11e8-84a2-9c684493a2b7.png)

In bash session I have correct locale:
```
bash-3.2$ set |grep LANG
LANG=ru_RU.UTF-8

bash-3.2$ locale
LANG="ru_RU.UTF-8"
LC_COLLATE="ru_RU.UTF-8"
LC_CTYPE="ru_RU.UTF-8"
LC_MESSAGES="ru_RU.UTF-8"
LC_MONETARY="ru_RU.UTF-8"
LC_NUMERIC="ru_RU.UTF-8"
LC_TIME="ru_RU.UTF-8"
LC_ALL=
```
But I'm not sure that all of this variables are set in default environment (when I started the application with mouse doubleclick)

(remark: BibleTime 2.10.2 doesn't have this problem)

**Comment by mgruner** [comment] 2018-06-25 11:37
I see this too. We don't have any custom code for the language handling, but rely on QLocale::system(). Not sure how to proceed here. @gholmlund and @jaakristioja , any suggestions?

```
    //first install QT's own translations
    QTranslator qtTranslator;
    if (qtTranslator.load("qt_" + QLocale::system().name(),
                          QLibraryInfo::location(QLibraryInfo::TranslationsPath)))
        app.installTranslator(&qtTranslator);
    //then our own
    QTranslator BibleTimeTranslator;
    BibleTimeTranslator.load( QString("bibletime_ui_").append(QLocale::system().name()), DU::getLocaleDir().canonicalPath());
    app.installTranslator(&BibleTimeTranslator);
```

**Comment by jaakristioja** [comment] 2018-06-25 13:28
It seems that Qt fails to pick up the system language when started from the Applications folder, because `LANG` is not properly set in the environment. Looks awfully like Qt is not doing enough to properly detect the system language. We could probably work around this bug by using some native OS X API instead.

[This Apple.StackExchange answer](https://apple.stackexchange.com/a/21107) seems to indicate that it might be possible to have OS X set these environment variables so that they persist across reboots.

**Comment by jaakristioja** [comment] 2020-03-09 21:48
> I see this too. We don't have any custom code for the language handling, but rely on `QLocale::system()`.

As of commit abd0d2d63f3c3fd0008ef717c0d259ac9d7a564a we now rely on QLocale().

> Not sure how to proceed here. @gholmlund and @jaakristioja, any suggestions?

Might have been fixed with commit 2754edaff5e1e39d9a0317091b4d04c142bb96d5.

**Comment by gholmlund** [comment] 2020-03-23 00:40
@jaakristioja   I tested the beta2 version and reproduced this issue. I tested the latest and it did not have this issue.

**Comment by jaakristioja** [comment] 2020-04-03 20:46
Thank you for testing, @gholmlund!

Ok, let's assume this is fixed. Please reopen if this still occurs with git master or any release newer than 3.0 beta 2.

**Closed by jaakristioja** 2020-04-03 20:46 UTC
Labels: component: Frontend, type: BUG
