### ISSUE TITLE
[ENHANCEMENT] 

### ISSUE THREAD

**Issue by cmahte** [bibletime/bibletime#404] opened 2022-08-08 15:32 UTC
**Is your feature request related to a problem? Please describe.**
many languages are only displayed as a 3 letter code. 

**Describe the solution you'd like**
(where is the language info coming from.. only the .conf files?) 

As a fallback to whatever language information is currently used, as a fallback include the 3 letter code AND the [IANA registry](http://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) description. This will (virtually) eliminate that section of 3letter codes only. 

**Describe alternatives you've considered**
If there is a translation table. I will help update it with this list. If it's only coming from the .conf file.... that's not my area of ability, but I will help if allowed. 

**Additional context**

**Comment by jaakristioja** [comment] 2023-08-23 15:19
Duplicate of #345. See also #347.

**Closed by jaakristioja** 2023-08-23 15:19 UTC
Labels: type: ENHANCEMENT
